### ISSUE TITLE
Support Request: old curtain still visible

### ISSUE THREAD

**Issue by barabba9174** [OpenWonderLabs/homebridge-switchbot#34] opened 2021-09-28 08:10 UTC
### Describe Your Problem

Disconnected curtain still visible (I've returned it to Amazon)

### Config for homebridge-switchbot

```shell
{
    "name": ".....",
    "credentials": {
        "openToken": "...",
        "notice": "Keep your token a secret!"
    },
    "options": {
        "hide_device": [
            "C7BF1643E5D7"
        ],
        "curtain": {
            "disable_group": false
        }
    },
    "platform": "SwitchBot"
}
```

### Screenshots

![image](https://user-images.githubusercontent.com/7170222/135047869-8e8d2b07-039f-44bc-8f9d-dd6a6bac90a0.png)
![image](https://user-images.githubusercontent.com/7170222/135048203-7d8cdd88-668a-46e8-8ded-dbd3a19cc7bd.png)

### Device & Model

 SWITCHBOT-CURTAIN-W0701600

### Node.js Version

v14.17.6

### NPM Version

v6.14.15

### Homebridge Version

v1.3.4

### Homebridge SwitchBot Plugin Version

v0.1.1

### Homebridge Config UI X Plugin Version

v4.41.2

### Operating System

Raspbian

**Comment by donavanbecker** [comment] 2021-09-28 10:06
Duplicate of #35

**Closed as completed** 2021-09-28 10:06 UTC
Labels: question
