### ISSUE TITLE
Feature Request: Pan/Tilt Cam

### ISSUE THREAD

**Issue by dferch** [OpenWonderLabs/homebridge-switchbot#640] opened 2023-01-04 21:49 UTC
### Problem

Pan/Tilt Cam not supported

### Solution

Add support for the Pan/Tilt Cam

### Alternatives

none

**Comment by donavanbecker** [comment] 2023-01-04 22:58
Duplicate of #429

**Closed as not planned by donavanbecker** 2023-01-04 22:58 UTC
Labels: enhancement
