### ISSUE TITLE
Bug: Bot device configured in this plugin as "Mode: Switch" automatically reverts to "On" state in HomeKit after each Switchbot API poll

### ISSUE THREAD

**Issue by Kositch** [OpenWonderLabs/homebridge-switchbot#1021] opened 2024-08-07 04:46 UTC
### Describe the Bug

Switchbot Bot device set as "Mode: Press" in Switchbot official app. In this plugin config that same device set to "Mode: Switch" to behave like switch On/Off persisting its state - sending "Press" command to Bot device when operating switch. When Homekit switch of this device is turned On it presses the Bot device and when turned Off it presses Bot device again. The state of switch in homekit should remain same until next pressing of switch. Current behaviour in "3.7.1 beta 10"  is that after turning the homekit switch Off it goes unexpectedly On again after next Switchbot API poll - see logs. When downgraded plugin to "3.4.0" version, it behaves as it should - when switch in homekit is Off it remains off until next switch pressing and turning it On.

### To Reproduce

Bot device as  "Mode: Press" in Switchbot app, in plugin config  "Mode: Switch", turn homekit switch of this device to Off and wait until next API poll and the homekit switch goes On without any reason.

### Expected Behavior

Switch in homekit should remain in current state (On/Off) until next switching and not automatically turn On based on API poll (i.e. it should persist its state until next oprating of that switch).

### Relevant Log Output

```shell
[37m[06/08/2024, 22:01:44] [39m[36m[SwitchBot][39m [DEBUG] Bot: Ohrev TUV openAPIRefreshStatus
[37m[06/08/2024, 22:01:46] [39m[36m[SwitchBot][39m [DEBUG] Bot: Ohrev TUV statusCode: 200, deviceStatus: {"statusCode":100,"body":{"deviceId":"C63430351E48","deviceType":"Bot","hubDeviceId":"D59FD8A01843","version":"V6.6","power":"on","battery":99,"deviceMode":"pressMode"},"message":"success"}
[37m[06/08/2024, 22:01:46] [39m[36m[SwitchBot][39m [32m[DEBUG] Bot: Ohrev TUV statusCode: 200, deviceStatus: {"statusCode":100,"body":{"deviceId":"C63430351E48","deviceType":"Bot","hubDeviceId":"D59FD8A01843","version":"V6.6","power":"on","battery":99,"deviceMode":"pressMode"},"message":"success"}[39m
[37m[06/08/2024, 22:01:46] [39m[36m[SwitchBot][39m [DEBUG] Bot: Ohrev TUV openAPIparseStatus
[37m[06/08/2024, 22:01:46] [39m[36m[SwitchBot][39m [DEBUG] Bot: Ohrev TUV (power, battery, deviceMode) = API:(on, 99, switch), current:(false, 99, switch)
[37m[06/08/2024, 22:01:46] [39m[36m[SwitchBot][39m [DEBUG] Bot: Ohrev TUV On: true
[37m[06/08/2024, 22:01:46] [39m[36m[SwitchBot][39m [DEBUG] Bot: Ohrev TUV BatteryLevel: 99
[37m[06/08/2024, 22:01:46] [39m[36m[SwitchBot][39m [DEBUG] Bot: Ohrev TUV StatusLowBattery: 0
[37m[06/08/2024, 22:01:46] [39m[36m[SwitchBot][39m [DEBUG] Bot: Ohrev TUV Firmware Version: 6.6
[37m[06/08/2024, 22:01:46] [39m[36m[SwitchBot][39m [DEBUG] Bot: Ohrev TUV version: 6.6
[37m[06/08/2024, 22:01:46] [39m[36m[SwitchBot][39m [DEBUG] Bot: Ohrev TUV updateHomeKitCharacteristics
[37m[06/08/2024, 22:01:46] [39m[36m[SwitchBot][39m [DEBUG] Bot: Ohrev TUV updateCharacteristic BatteryLevel: 99
[37m[06/08/2024, 22:01:46] [39m[36m[SwitchBot][39m [DEBUG] Bot: Ohrev TUV updateCharacteristic StatusLowBattery: 0
[37m[06/08/2024, 22:01:46] [39m[36m[SwitchBot][39m [DEBUG] Bot: Ohrev TUV updateCharacteristic On: true
```

### Config for homebridge-switchbot

```shell
Config of affected Bot device:

        "devices": [
            {
                "deviceId": "C63430351E48",
                "configDeviceName": "Ohrev TUV",
                "configDeviceType": "Bot",
                "connectionType": "OpenAPI",
                "bot": {
                    "mode": "switch",
                    "deviceType": "switch",
                    "doublePress": 1,
                    "pushRatePress": 5
                },
                "firmware": "6.6",
                "logging": "none"
            },
```

### Device and Model

Bot FW 6.6

### Node.js Version

v20.16.0

### NPM Version

N/A

### Homebridge Version

v1.8.4 

### Homebridge Switchbot Plugin Version

3.7.1 beta 10

### Operating System

Raspbian

**Comment by rafadiazr** [comment] 2024-08-10 10:45
Same issue here with a Smart Lock when using the latch option. I could reproduce the issue with the plugin version v3.7.0, v3.6.0, v3.5.1. It is not happening in plugin version v3.4.0.

**Comment by jaywick** [comment] 2024-08-11 13:58
Experiencing similar issue. This ticket looks related https://github.com/OpenWonderLabs/homebridge-switchbot/issues/1004

**Comment by sonsongithub** [comment] 2024-08-27 01:39
I think that a similar issue is happening on my ceiling lights.
In my case, homebridge's status automatically reverts to "Off" in a few seconds after turning on it using HomeKit.
But, the real ceiling light is not turned off by homebridge.
This issue could be reproduced with the plugin version v3.7.1beta, v3.7.0, v3.6.0, v3.5.1. It is not happening in plugin version v3.4.0.

**Comment by donavanbecker** [comment] 2024-09-10 21:37
Can you try the latest beta: 

[![npm version](https://badgen.net/badge/homebridge-switchbot@beta/>=3.7.1-beta.19/orange)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

[Click here to find out how to install Beta](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Beta-Version)

**Comment by rafadiazr** [comment] 2024-09-11 06:59
In my case, I still have the same issue on 3.7.1-beta19 and 3.7.1-beta23.

Would it help if we provide you with any logs?

**Comment by donavanbecker** [comment] 2024-09-11 10:42
logs always help

**Comment by sonsongithub** [comment] 2024-09-11 11:32
I've tried v3.7.1-beta.29 and v3.8.0.

But the ceiling lights do not work on these versions.

```
Loading logs using native method...
File: /var/lib/homebridge/homebridge.log: 0
[11/09/2024, 20:23:47] [SwitchBot] Plug: Mixer statusCode: 200, deviceStatus: {"statusCode":100,"body":{,"deviceType":"Plug",,"power":"on","version":"V2.0"},"message":"success"}
[11/09/2024, 20:23:47] [SwitchBot] [DEBUG] Plug: Mixer statusCode: 200, deviceStatus: {"statusCode":100,"body":{,"deviceType":"Plug",,"power":"on","version":"V2.0"},"message":"success"}
[11/09/2024, 20:23:47] [SwitchBot] Plug: Mixer openAPIparseStatus
[11/09/2024, 20:23:47] [SwitchBot] Plug: Mixer (powerState) = OpenAPI: (on), current:(true)
[11/09/2024, 20:23:47] [SwitchBot] Plug: Mixer On: true
[11/09/2024, 20:23:47] [SwitchBot] Plug: Mixer Firmware Version: 2.0
[11/09/2024, 20:23:47] [SwitchBot] [DEBUG] Plug: Mixer version: 2.0
[11/09/2024, 20:23:47] [SwitchBot] Plug: Mixer updateCharacteristic On: true
[11/09/2024, 20:23:47] [SwitchBot] [DEBUG] Plug: Mixer On context before: true
[11/09/2024, 20:23:47] [SwitchBot] [DEBUG] Plug: Mixer On context after: true
[11/09/2024, 20:23:47] [SwitchBot] Ceiling Light: Studio Light statusCode: 200, deviceStatus: {"statusCode":100,"body":{,"deviceType":"Ceiling Light",,"power":"on","brightness":77,"colorTemperature":4425,"version":"V1.3-0.4"},"message":"success"}
[11/09/2024, 20:23:47] [SwitchBot] [DEBUG] Ceiling Light: Studio Light statusCode: 200, deviceStatus: {"statusCode":100,"body":{,"deviceType":"Ceiling Light",,"power":"on","brightness":77,"colorTemperature":4425,"version":"V1.3-0.4"},"message":"success"}
[11/09/2024, 20:23:47] [SwitchBot] Ceiling Light: Studio Light openAPIparseStatus
[11/09/2024, 20:23:47] [SwitchBot] Ceiling Light: Studio Light (power, brightness, colorTemperature) = OpenAPI:(on, 77, 4425), current:(on, 77, 226)
[11/09/2024, 20:23:47] [SwitchBot] Ceiling Light: Studio Light On: on
[11/09/2024, 20:23:47] [SwitchBot] Ceiling Light: Studio Light Brightness: 77
[11/09/2024, 20:23:47] [SwitchBot] Ceiling Light: Studio Light ColorTemperature: 226
[11/09/2024, 20:23:47] [SwitchBot] Ceiling Light: Studio Light Firmware Version: 1.3
[11/09/2024, 20:23:47] [SwitchBot] [DEBUG] Ceiling Light: Studio Light version: 1.3
[11/09/2024, 20:23:47] [SwitchBot] Ceiling Light: Studio Light updateCharacteristic On: on
[11/09/2024, 20:23:47] [SwitchBot] [DEBUG] Ceiling Light: Studio Light On context before: on
[11/09/2024, 20:23:47] [SwitchBot] [DEBUG] Ceiling Light: Studio Light On context after: on
[11/09/2024, 20:23:47] [SwitchBot] Ceiling Light: Studio Light updateCharacteristic Brightness: 77
[11/09/2024, 20:23:47] [SwitchBot] [DEBUG] Ceiling Light: Studio Light Brightness context before: 77
[11/09/2024, 20:23:47] [SwitchBot] [DEBUG] Ceiling Light: Studio Light Brightness context after: 77
[11/09/2024, 20:23:47] [SwitchBot] Ceiling Light: Studio Light updateCharacteristic ColorTemperature: 226
[11/09/2024, 20:23:47] [SwitchBot] [DEBUG] Ceiling Light: Studio Light ColorTemperature context before: 226
[11/09/2024, 20:23:47] [SwitchBot] [DEBUG] Ceiling Light: Studio Light ColorTemperature context after: 226
[11/09/2024, 20:23:47] [SwitchBot] Ceiling Light: Studio Light updateCharacteristic Hue: 0
[11/09/2024, 20:23:47] [SwitchBot] [DEBUG] Ceiling Light: Studio Light Hue context before: 0
[11/09/2024, 20:23:47] [SwitchBot] [DEBUG] Ceiling Light: Studio Light Hue context after: 0
[11/09/2024, 20:23:47] [SwitchBot] Ceiling Light: Studio Light updateCharacteristic Saturation: 0
[11/09/2024, 20:23:47] [SwitchBot] [DEBUG] Ceiling Light: Studio Light Saturation context before: 0
[11/09/2024, 20:23:47] [SwitchBot] [DEBUG] Ceiling Light: Studio Light Saturation context after: 0
[11/09/2024, 20:23:50] [Homebridge UI] Terminal session ended.
[11/09/2024, 20:23:53] [SwitchBot] Ceiling Light: Studio Light No Changes, Set On: true
[11/09/2024, 20:23:53] [SwitchBot] Ceiling Light: Studio Light openAPIpushChanges[11/09/2024, 20:23:54] [SwitchBot] Ceiling Light: Studio Light statusCode: 200, deviceStatus: {"statusCode":100,"body":{"items":[{,"code":100,"status":{"fold":6,"model":"sun",,"power":"on","brightness":77,"colorTemperature":4425},"message":"success"}]},"message":"success"}
[11/09/2024, 20:23:54] [SwitchBot] [DEBUG] Ceiling Light: Studio Light statusCode: 200, deviceStatus: {"statusCode":100,"body":{"items":[{,"code":100,"status":{"fold":6,"model":"sun",,"power":"on","brightness":77,"colorTemperature":4425},"message":"success"}]},"message":"success"}
[11/09/2024, 20:23:54] [SwitchBot] Ceiling Light: Studio Light updateCharacteristic On: true
[11/09/2024, 20:23:54] [SwitchBot] Ceiling Light: Studio Light updateCharacteristic Brightness: 77
[11/09/2024, 20:23:54] [SwitchBot] Ceiling Light: Studio Light updateCharacteristic ColorTemperature: 226
[11/09/2024, 20:23:54] [SwitchBot] Ceiling Light: Studio Light updateCharacteristic Hue: 0
[11/09/2024, 20:23:54] [SwitchBot] Ceiling Light: Studio Light updateCharacteristic Saturation: 0
[11/09/2024, 20:23:54] [SwitchBot] Ceiling Light: Studio Light On: true
[11/09/2024, 20:23:54] [SwitchBot] Ceiling Light: Studio Light Brightness: 77
[11/09/2024, 20:23:54] [SwitchBot] [DEBUG] Ceiling Light: Studio Light On context before: on
[11/09/2024, 20:23:54] [SwitchBot] [DEBUG] Ceiling Light: Studio Light On context after: true
[11/09/2024, 20:23:54] [SwitchBot] [DEBUG] Ceiling Light: Studio Light Brightness context before: 77
[11/09/2024, 20:23:54] [SwitchBot] [DEBUG] Ceiling Light: Studio Light Brightness context after: 77
[11/09/2024, 20:23:54] [SwitchBot] [DEBUG] Ceiling Light: Studio Light ColorTemperature context before: 226
[11/09/2024, 20:23:54] [SwitchBot] [DEBUG] Ceiling Light: Studio Light ColorTemperature context after: 226
[11/09/2024, 20:23:54] [SwitchBot] [DEBUG] Ceiling Light: Studio Light Hue context before: 0
[11/09/2024, 20:23:54] [SwitchBot] [DEBUG] Ceiling Light: Studio Light Hue context after: 0
[11/09/2024, 20:23:54] [SwitchBot] [DEBUG] Ceiling Light: Studio Light Saturation context before: 0
[11/09/2024, 20:23:54] [SwitchBot] [DEBUG] Ceiling Light: Studio Light Saturation context after: 0
[11/09/2024, 20:23:54] [SwitchBot] Ceiling Light: Studio Light pushBrightnessChanges
[11/09/2024, 20:23:54] [SwitchBot] Ceiling Light: Studio Light No changes (pushBrightnessChanges), Brightness: 77, BrightnessCached: 77
[11/09/2024, 20:23:54] [SwitchBot] Ceiling Light: Studio Light ColorTemperature: 226
[11/09/2024, 20:23:54] [SwitchBot] Ceiling Light: Studio Light pushColorTemperatureChanges
[11/09/2024, 20:23:54] [SwitchBot] Ceiling Light: Studio Light No changes (pushColorTemperatureChanges), ColorTemperature: 226, ColorTemperatureCached: 226
[11/09/2024, 20:23:54] [SwitchBot] Ceiling Light: Studio Light Hue: 0, Saturation: 0
[11/09/2024, 20:23:54] [SwitchBot] Ceiling Light: Studio Light pushHueSaturationChanges
[11/09/2024, 20:23:54] [SwitchBot] Ceiling Light: Studio Light No changes (pushHueSaturationChanges), Hue: 0, HueCached: 0, Saturation: 0, SaturationCached: 0[11/09/2024, 20:23:58] [Homebridge UI] Starting terminal session
[11/09/2024, 20:24:01] [Homebridge UI] Terminal session ended.
[11/09/2024, 20:24:03] [Homebridge UI] Starting terminal session[11/09/2024, 20:24:09] [SwitchBot] Ceiling Light: Studio Light openAPIRefreshStatus
[11/09/2024, 20:24:10] [SwitchBot] Ceiling Light: Studio Light statusCode: 200, deviceStatus: {"statusCode":100,"body":{,"deviceType":"Ceiling Light",,"power":"on","brightness":77,"colorTemperature":4425,"version":"V1.3-0.4"},"message":"success"}
[11/09/2024, 20:24:10] [SwitchBot] [DEBUG] Ceiling Light: Studio Light statusCode: 200, deviceStatus: {"statusCode":100,"body":{,"deviceType":"Ceiling Light",,"power":"on","brightness":77,"colorTemperature":4425,"version":"V1.3-0.4"},"message":"success"}
[11/09/2024, 20:24:10] [SwitchBot] Ceiling Light: Studio Light openAPIparseStatus
[11/09/2024, 20:24:10] [SwitchBot] Ceiling Light: Studio Light (power, brightness, colorTemperature) = OpenAPI:(on, 77, 4425), current:(true, 77, 226)
[11/09/2024, 20:24:10] [SwitchBot] Ceiling Light: Studio Light On: on
[11/09/2024, 20:24:10] [SwitchBot] Ceiling Light: Studio Light Brightness: 77
[11/09/2024, 20:24:10] [SwitchBot] Ceiling Light: Studio Light ColorTemperature: 226
[11/09/2024, 20:24:10] [SwitchBot] Ceiling Light: Studio Light Firmware Version: 1.3
[11/09/2024, 20:24:10] [SwitchBot] [DEBUG] Ceiling Light: Studio Light version: 1.3
[11/09/2024, 20:24:10] [SwitchBot] Ceiling Light: Studio Light updateCharacteristic On: on
[11/09/2024, 20:24:10] [SwitchBot] [DEBUG] Ceiling Light: Studio Light On context before: true
[11/09/2024, 20:24:10] [SwitchBot] [DEBUG] Ceiling Light: Studio Light On context after: on
[11/09/2024, 20:24:10] [SwitchBot] [DEBUG] Ceiling Light: Studio Light Brightness context before: 77
[11/09/2024, 20:24:10] [SwitchBot] Ceiling Light: Studio Light updateCharacteristic Brightness: 77
[11/09/2024, 20:24:10] [SwitchBot] [DEBUG] Ceiling Light: Studio Light Brightness context after: 77
[11/09/2024, 20:24:10] [SwitchBot] [DEBUG] Ceiling Light: Studio Light ColorTemperature context before: 226
[11/09/2024, 20:24:10] [SwitchBot] Ceiling Light: Studio Light updateCharacteristic ColorTemperature: 226
[11/09/2024, 20:24:10] [SwitchBot] [DEBUG] Ceiling Light: Studio Light ColorTemperature context after: 226
[11/09/2024, 20:24:10] [SwitchBot] [DEBUG] Ceiling Light: Studio Light Hue context before: 0
[11/09/2024, 20:24:10] [SwitchBot] Ceiling Light: Studio Light updateCharacteristic Hue: 0
[11/09/2024, 20:24:10] [SwitchBot] [DEBUG] Ceiling Light: Studio Light Hue context after: 0
[11/09/2024, 20:24:10] [SwitchBot] Ceiling Light: Studio Light updateCharacteristic Saturation: 0
[11/09/2024, 20:24:10] [SwitchBot] [DEBUG] Ceiling Light: Studio Light Saturation context before: 0
[11/09/2024, 20:24:10] [SwitchBot] [DEBUG] Ceiling Light: Studio Light Saturation context after: 0[11/09/2024, 20:24:19] [Homebridge UI] Terminal session ended.
[11/09/2024, 20:24:21] [Homebridge UI] Starting terminal session[11/09/2024, 20:24:27] [Homebridge UI] Terminal session ended.
[11/09/2024, 20:24:29] [SwitchBot] Ceiling Light: Studio Light No Changes, Set On: true
[11/09/2024, 20:24:30] [SwitchBot] Ceiling Light: Studio Light openAPIpushChanges[11/09/2024, 20:24:30] [Homebridge UI] Starting terminal session
[11/09/2024, 20:24:31] [SwitchBot] Ceiling Light: Studio Light statusCode: 200, deviceStatus: {"statusCode":100,"body":{"items":[{,"code":100,"status":{"fold":6,"model":"sun",,"power":"on","brightness":77,"colorTemperature":4425},"message":"success"}]},"message":"success"}
[11/09/2024, 20:24:31] [SwitchBot] [DEBUG] Ceiling Light: Studio Light statusCode: 200, deviceStatus: {"statusCode":100,"body":{"items":[{,"code":100,"status":{"fold":6,"model":"sun",,"power":"on","brightness":77,"colorTemperature":4425},"message":"success"}]},"message":"success"}
[11/09/2024, 20:24:31] [SwitchBot] Ceiling Light: Studio Light updateCharacteristic On: true
[11/09/2024, 20:24:31] [SwitchBot] Ceiling Light: Studio Light updateCharacteristic Brightness: 77
[11/09/2024, 20:24:31] [SwitchBot] Ceiling Light: Studio Light updateCharacteristic ColorTemperature: 226
[11/09/2024, 20:24:31] [SwitchBot] Ceiling Light: Studio Light updateCharacteristic Hue: 0
[11/09/2024, 20:24:31] [SwitchBot] Ceiling Light: Studio Light updateCharacteristic Saturation: 0
[11/09/2024, 20:24:31] [SwitchBot] Ceiling Light: Studio Light On: true
[11/09/2024, 20:24:31] [SwitchBot] Ceiling Light: Studio Light Brightness: 77
[11/09/2024, 20:24:31] [SwitchBot] Ceiling Light: Studio Light pushBrightnessChanges
[11/09/2024, 20:24:31] [SwitchBot] Ceiling Light: Studio Light No changes (pushBrightnessChanges), Brightness: 77, BrightnessCached: 77
[11/09/2024, 20:24:31] [SwitchBot] Ceiling Light: Studio Light ColorTemperature: 226
[11/09/2024, 20:24:31] [SwitchBot] Ceiling Light: Studio Light pushColorTemperatureChanges
[11/09/2024, 20:24:31] [SwitchBot] Ceiling Light: Studio Light No changes (pushColorTemperatureChanges), ColorTemperature: 226, ColorTemperatureCached: 226
[11/09/2024, 20:24:31] [SwitchBot] Ceiling Light: Studio Light Hue: 0, Saturation: 0
[11/09/2024, 20:24:31] [SwitchBot] [DEBUG] Ceiling Light: Studio Light On context before: on
[11/09/2024, 20:24:31] [SwitchBot] [DEBUG] Ceiling Light: Studio Light On context after: true
[11/09/2024, 20:24:31] [SwitchBot] [DEBUG] Ceiling Light: Studio Light Brightness context before: 77
[11/09/2024, 20:24:31] [SwitchBot] [DEBUG] Ceiling Light: Studio Light Brightness context after: 77
[11/09/2024, 20:24:31] [SwitchBot] [DEBUG] Ceiling Light: Studio Light ColorTemperature context before: 226
[11/09/2024, 20:24:31] [SwitchBot] [DEBUG] Ceiling Light: Studio Light ColorTemperature context after: 226
[11/09/2024, 20:24:31] [SwitchBot] [DEBUG] Ceiling Light: Studio Light Hue context before: 0
[11/09/2024, 20:24:31] [SwitchBot] [DEBUG] Ceiling Light: Studio Light Hue context after: 0
[11/09/2024, 20:24:31] [SwitchBot] [DEBUG] Ceiling Light: Studio Light Saturation context before: 0
[11/09/2024, 20:24:31] [SwitchBot] [DEBUG] Ceiling Light: Studio Light Saturation context after: 0
[11/09/2024, 20:24:31] [SwitchBot] Ceiling Light: Studio Light pushHueSaturationChanges
[11/09/2024, 20:24:31] [SwitchBot] Ceiling Light: Studio Light No changes (pushHueSaturationChanges), Hue: 0, HueCached: 0, Saturation: 0, SaturationCached: 0
[11/09/2024, 20:24:46] [SwitchBot] Ceiling Light: Studio Light openAPIRefreshStatus
[11/09/2024, 20:24:47] [SwitchBot] Ceiling Light: Studio Light statusCode: 200, deviceStatus: {"statusCode":100,"body":{,"deviceType":"Ceiling Light",,"power":"on","brightness":77,"colorTemperature":4425,"version":"V1.3-0.4"},"message":"success"}
[11/09/2024, 20:24:47] [SwitchBot] [DEBUG] Ceiling Light: Studio Light statusCode: 200, deviceStatus: {"statusCode":100,"body":{,"deviceType":"Ceiling Light",,"power":"on","brightness":77,"colorTemperature":4425,"version":"V1.3-0.4"},"message":"success"}
[11/09/2024, 20:24:47] [SwitchBot] Ceiling Light: Studio Light openAPIparseStatus
[11/09/2024, 20:24:47] [SwitchBot] Ceiling Light: Studio Light (power, brightness, colorTemperature) = OpenAPI:(on, 77, 4425), current:(true, 77, 226)
[11/09/2024, 20:24:47] [SwitchBot] Ceiling Light: Studio Light On: on
[11/09/2024, 20:24:47] [SwitchBot] Ceiling Light: Studio Light Brightness: 77
[11/09/2024, 20:24:47] [SwitchBot] Ceiling Light: Studio Light ColorTemperature: 226
[11/09/2024, 20:24:47] [SwitchBot] Ceiling Light: Studio Light Firmware Version: 1.3
[11/09/2024, 20:24:47] [SwitchBot] [DEBUG] Ceiling Light: Studio Light version: 1.3
[11/09/2024, 20:24:47] [SwitchBot] Ceiling Light: Studio Light updateCharacteristic On: on
[11/09/2024, 20:24:47] [SwitchBot] [DEBUG] Ceiling Light: Studio Light On context before: true
[11/09/2024, 20:24:47] [SwitchBot] [DEBUG] Ceiling Light: Studio Light On context after: on
[11/09/2024, 20:24:47] [SwitchBot] Ceiling Light: Studio Light updateCharacteristic Brightness: 77
[11/09/2024, 20:24:47] [SwitchBot] [DEBUG] Ceiling Light: Studio Light Brightness context before: 77
[11/09/2024, 20:24:47] [SwitchBot] [DEBUG] Ceiling Light: Studio Light Brightness context after: 77
[11/09/2024, 20:24:47] [SwitchBot] Ceiling Light: Studio Light updateCharacteristic ColorTemperature: 226
[11/09/2024, 20:24:47] [SwitchBot] [DEBUG] Ceiling Light: Studio Light ColorTemperature context before: 226
[11/09/2024, 20:24:47] [SwitchBot] [DEBUG] Ceiling Light: Studio Light ColorTemperature context after: 226
[11/09/2024, 20:24:47] [SwitchBot] Ceiling Light: Studio Light updateCharacteristic Hue: 0
[11/09/2024, 20:24:47] [SwitchBot] [DEBUG] Ceiling Light: Studio Light Hue context before: 0
[11/09/2024, 20:24:47] [SwitchBot] [DEBUG] Ceiling Light: Studio Light Hue context after: 0
[11/09/2024, 20:24:47] [SwitchBot] Ceiling Light: Studio Light updateCharacteristic Saturation: 0
[11/09/2024, 20:24:47] [SwitchBot] [DEBUG] Ceiling Light: Studio Light Saturation context before: 0
[11/09/2024, 20:24:47] [SwitchBot] [DEBUG] Ceiling Light: Studio Light Saturation context after: 0
```

**Comment by donavanbecker** [comment] 2024-10-09 18:30
Okay I have pushed out a new beta, this beta is a major change. all config will need to be reset and may change during the beta phase. if anyone is having any other issues with bots please try.


[![npm version](https://badgen.net/badge/homebridge-switchbot@beta/>=4.0.0-beta.1/orange)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

[Click here to find out how to install Beta](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Beta-Version)

**Comment by donavanbecker** [comment] 2024-10-12 04:28
Closing all issues now that v4.0.0 is out. If you are still having an issue after trying v4.0.0, please open a new issue. Keep in mind v4.0.0 has some breaking changes with the config. You will need to re set your config up, however there are some nice added bonuses since you can set settings at a deviceType level or individual level.

**Closed as completed by donavanbecker** 2024-10-12 04:28 UTC
Labels: bug, pinned
