### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by kylewhirl** [OpenWonderLabs/homebridge-switchbot#150] opened 2021-12-19 10:32 UTC
### Describe The Bug

Curtains say 1% open even though they are fully closed

### To Reproduce

Not sure, it’s never worked for me. My curtains always say 1% open when trying to close them

### Expected behavior

They should be closed instead of 1% open

### Relevant log output

```shell
19/12/2021, 02:17:19] [SwitchBot] [DEBUG] Bot: Bedroom Door OpenAPI refreshStatus
[19/12/2021, 02:17:20] [SwitchBot] [DEBUG] Curtain: Right Curtain OpenAPI refreshStatus
[19/12/2021, 02:17:20] [SwitchBot] [DEBUG] Curtain: Left Curtain OpenAPI refreshStatus
[19/12/2021, 02:17:20] [SwitchBot] [DEBUG] Bot: Bedroom Door refreshStatus: {"statusCode":100,"body":{"deviceId":"C465D0A162F0","deviceType":"Bot","hubDeviceId":"E78C196D3920","power":"off"},"message":"success"}
[19/12/2021, 02:17:20] [SwitchBot] [DEBUG] Bot: Bedroom Door OpenAPI parseStatus
[19/12/2021, 02:17:20] [SwitchBot] [DEBUG] Bot Bedroom Door On: false
[19/12/2021, 02:17:20] [SwitchBot] [DEBUG] Bot: Bedroom Door updateCharacteristic On: false
[19/12/2021, 02:17:20] [SwitchBot] [DEBUG] Curtain: Right Curtain refreshStatus: {"statusCode":100,"body":{"deviceId":"C5B51B79449C","deviceType":"Curtain","hubDeviceId":"E78C196D3920","calibrate":true,"group":false,"moving":false,"slidePosition":99},"message":"success"}
[19/12/2021, 02:17:20] [SwitchBot] [DEBUG] Curtain: Right Curtain OpenAPI parseStatus
[19/12/2021, 02:17:20] [SwitchBot] [DEBUG] Curtain Right Curtain CurrentPosition: 1
[19/12/2021, 02:17:20] [SwitchBot] [DEBUG] Curtain: Right Curtain Standby, CurrentPosition: 1
[19/12/2021, 02:17:20] [SwitchBot] [DEBUG] Curtain: Right Curtain CurrentPosition: 1, TargetPosition: 1, PositionState: 2,
[19/12/2021, 02:17:20] [SwitchBot] [DEBUG] Curtain: Right Curtain CurrentAmbientLightLevel: 6001
[19/12/2021, 02:17:20] [SwitchBot] [DEBUG] Curtain: Right Curtain updateCharacteristic CurrentPosition: 1
[19/12/2021, 02:17:20] [SwitchBot] [DEBUG] Curtain: Right Curtain updateCharacteristic PositionState: 2
[19/12/2021, 02:17:20] [SwitchBot] [DEBUG] Curtain: Right Curtain updateCharacteristic TargetPosition: 1
[19/12/2021, 02:17:20] [SwitchBot] [DEBUG] Curtain: Right Curtain updateCharacteristic CurrentAmbientLightLevel: 6001
[19/12/2021, 02:17:20] [SwitchBot] [DEBUG] Curtain: Left Curtain refreshStatus: {"statusCode":100,"body":{"deviceId":"CD1BE5DAAB3A","deviceType":"Curtain","hubDeviceId":"E78C196D3920","calibrate":true,"group":false,"moving":false,"slidePosition":99},"message":"success"}
[19/12/2021, 02:17:20] [SwitchBot] [DEBUG] Curtain: Left Curtain OpenAPI parseStatus
[19/12/2021, 02:17:20] [SwitchBot] [DEBUG] Curtain Left Curtain CurrentPosition: 1
[19/12/2021, 02:17:20] [SwitchBot] [DEBUG] Curtain: Left Curtain Standby, CurrentPosition: 1
[19/12/2021, 02:17:20] [SwitchBot] [DEBUG] Curtain: Left Curtain CurrentPosition: 1, TargetPosition: 1, PositionState: 2,
[19/12/2021, 02:17:20] [SwitchBot] [DEBUG] Curtain: Left Curtain CurrentAmbientLightLevel: 6001
[19/12/2021, 02:17:20] [SwitchBot] [DEBUG] Curtain: Left Curtain updateCharacteristic CurrentPosition: 1
[19/12/2021, 02:17:20] [SwitchBot] [DEBUG] Curtain: Left Curtain updateCharacteristic PositionState: 2
[19/12/2021, 02:17:20] [SwitchBot] [DEBUG] Curtain: Left Curtain updateCharacteristic TargetPosition: 1
[19/12/2021, 02:17:20] [SwitchBot] [DEBUG] Curtain: Left Curtain updateCharacteristic CurrentAmbientLightLevel: 6001
[19/12/2021, 02:18:36] [SwitchBot] [DEBUG] Curtain: Right Curtain TargetPosition: 0
[19/12/2021, 02:18:36] [SwitchBot] [DEBUG] Curtain: Right Curtain value: 0, CurrentPosition: 1
[19/12/2021, 02:18:36] [SwitchBot] [DEBUG] Curtain: Right Curtain OpenAPI pushChanges
[19/12/2021, 02:18:36] [SwitchBot] [DEBUG] Pushing 0
[19/12/2021, 02:18:36] [SwitchBot] Curtain: Right Curtain Sending request to SwitchBot API. command: setPosition, parameter: 0,ff,100, commandType: command
[19/12/2021, 02:18:36] [SwitchBot] [DEBUG] Curtain: Left Curtain TargetPosition: 0
[19/12/2021, 02:18:36] [SwitchBot] [DEBUG] Curtain: Left Curtain value: 0, CurrentPosition: 1
[19/12/2021, 02:18:36] [SwitchBot] [DEBUG] Curtain: Left Curtain OpenAPI pushChanges
[19/12/2021, 02:18:36] [SwitchBot] [DEBUG] Pushing 0
[19/12/2021, 02:18:36] [SwitchBot] Curtain: Left Curtain Sending request to SwitchBot API. command: setPosition, parameter: 0,ff,100, commandType: command
[19/12/2021, 02:18:37] [SwitchBot] [DEBUG] Curtain: Right Curtain pushchanges: {"statusCode":100,"body":{},"message":"success"}
[19/12/2021, 02:18:37] [SwitchBot] [DEBUG] Curtain: Right Curtain Command successfully sent.
[19/12/2021, 02:18:37] [SwitchBot] [DEBUG] Curtain: Left Curtain pushchanges: {"statusCode":100,"body":{},"message":"success"}
[19/12/2021, 02:18:37] [SwitchBot] [DEBUG] Curtain: Left Curtain Command successfully sent.
[19/12/2021, 02:18:38] [SwitchBot] [DEBUG] Curtain: Right Curtain Refresh Status When Moving, PositionState: 0
[19/12/2021, 02:18:38] [SwitchBot] [DEBUG] Curtain: Right Curtain OpenAPI refreshStatus
[19/12/2021, 02:18:38] [SwitchBot] [DEBUG] Curtain: Left Curtain Refresh Status When Moving, PositionState: 0
[19/12/2021, 02:18:38] [SwitchBot] [DEBUG] Curtain: Left Curtain OpenAPI refreshStatus
[19/12/2021, 02:18:38] [SwitchBot] [DEBUG] Curtain: Left Curtain refreshStatus: {"statusCode":100,"body":{"deviceId":"CD1BE5DAAB3A","deviceType":"Curtain","hubDeviceId":"E78C196D3920","calibrate":true,"group":false,"moving":false,"slidePosition":99},"message":"success"}
[19/12/2021, 02:18:38] [SwitchBot] [DEBUG] Curtain: Left Curtain OpenAPI parseStatus
[19/12/2021, 02:18:38] [SwitchBot] [DEBUG] Curtain Left Curtain CurrentPosition: 1
[19/12/2021, 02:18:38] [SwitchBot] Checking Left Curtain Status ...
[19/12/2021, 02:18:38] [SwitchBot] [DEBUG] Curtain: Left Curtain Standby, CurrentPosition: 1
[19/12/2021, 02:18:38] [SwitchBot] [DEBUG] Curtain: Left Curtain CurrentPosition: 1, TargetPosition: 0, PositionState: 0,
[19/12/2021, 02:18:38] [SwitchBot] [DEBUG] Curtain: Left Curtain CurrentAmbientLightLevel: 6001
[19/12/2021, 02:18:38] [SwitchBot] [DEBUG] Curtain: Left Curtain updateCharacteristic CurrentPosition: 1
[19/12/2021, 02:18:38] [SwitchBot] [DEBUG] Curtain: Left Curtain updateCharacteristic PositionState: 0
[19/12/2021, 02:18:38] [SwitchBot] [DEBUG] Curtain: Left Curtain updateCharacteristic TargetPosition: 0
[19/12/2021, 02:18:38] [SwitchBot] [DEBUG] Curtain: Left Curtain updateCharacteristic CurrentAmbientLightLevel: 6001
[19/12/2021, 02:18:38] [SwitchBot] [DEBUG] Curtain: Right Curtain refreshStatus: {"statusCode":100,"body":{"deviceId":"C5B51B79449C","deviceType":"Curtain","hubDeviceId":"CD1BE5DAAB3A","calibrate":true,"group":false,"moving":false,"slidePosition":100},"message":"success"}
[19/12/2021, 02:18:38] [SwitchBot] [DEBUG] Curtain: Right Curtain OpenAPI parseStatus
[19/12/2021, 02:18:38] [SwitchBot] [DEBUG] Curtain Right Curtain CurrentPosition: 0
[19/12/2021, 02:18:38] [SwitchBot] Checking Right Curtain Status ...
[19/12/2021, 02:18:38] [SwitchBot] [DEBUG] Curtain: Right Curtain Standby, CurrentPosition: 0
[19/12/2021, 02:18:38] [SwitchBot] [DEBUG] Curtain: Right Curtain CurrentPosition: 0, TargetPosition: 0, PositionState: 0,
[19/12/2021, 02:18:38] [SwitchBot] [DEBUG] Curtain: Right Curtain CurrentAmbientLightLevel: 6001
[19/12/2021, 02:18:38] [SwitchBot] [DEBUG] Curtain: Right Curtain updateCharacteristic CurrentPosition: 0
[19/12/2021, 02:18:38] [SwitchBot] [DEBUG] Curtain: Right Curtain updateCharacteristic PositionState: 0
[19/12/2021, 02:18:38] [SwitchBot] [DEBUG] Curtain: Right Curtain updateCharacteristic TargetPosition: 0
[19/12/2021, 02:18:38] [SwitchBot] [DEBUG] Curtain: Right Curtain updateCharacteristic CurrentAmbientLightLevel: 6001
[19/12/2021, 02:18:42] [SwitchBot] [DEBUG] Curtain: Right Curtain OpenAPI refreshStatus
[19/12/2021, 02:18:42] [SwitchBot] [DEBUG] Curtain: Left Curtain OpenAPI refreshStatus
[19/12/2021, 02:18:42] [SwitchBot] [DEBUG] Curtain: Right Curtain refreshStatus: {"statusCode":100,"body":{"deviceId":"C5B51B79449C","deviceType":"Curtain","hubDeviceId":"E78C196D3920","calibrate":true,"group":false,"moving":false,"slidePosition":100},"message":"success"}
[19/12/2021, 02:18:42] [SwitchBot] [DEBUG] Curtain: Right Curtain OpenAPI parseStatus
[19/12/2021, 02:18:42] [SwitchBot] [DEBUG] Curtain Right Curtain CurrentPosition: 0
[19/12/2021, 02:18:42] [SwitchBot] Checking Right Curtain Status ...
[19/12/2021, 02:18:42] [SwitchBot] [DEBUG] Curtain: Right Curtain Standby, CurrentPosition: 0
[19/12/2021, 02:18:42] [SwitchBot] [DEBUG] Curtain: Right Curtain CurrentPosition: 0, TargetPosition: 0, PositionState: 0,
[19/12/2021, 02:18:42] [SwitchBot] [DEBUG] Curtain: Right Curtain CurrentAmbientLightLevel: 6001
[19/12/2021, 02:18:42] [SwitchBot] [DEBUG] Curtain: Right Curtain updateCharacteristic CurrentPosition: 0
[19/12/2021, 02:18:42] [SwitchBot] [DEBUG] Curtain: Right Curtain updateCharacteristic PositionState: 0
[19/12/2021, 02:18:42] [SwitchBot] [DEBUG] Curtain: Right Curtain updateCharacteristic TargetPosition: 0
[19/12/2021, 02:18:42] [SwitchBot] [DEBUG] Curtain: Right Curtain updateCharacteristic CurrentAmbientLightLevel: 6001
[19/12/2021, 02:18:43] [SwitchBot] [DEBUG] Curtain: Right Curtain Refresh Status When Moving, PositionState: 0
[19/12/2021, 02:18:43] [SwitchBot] [DEBUG] Curtain: Right Curtain OpenAPI refreshStatus
[19/12/2021, 02:18:43] [SwitchBot] [DEBUG] Curtain: Left Curtain refreshStatus: {"statusCode":100,"body":{"deviceId":"CD1BE5DAAB3A","deviceType":"Curtain","hubDeviceId":"E78C196D3920","calibrate":true,"group":false,"moving":false,"slidePosition":99},"message":"success"}
[19/12/2021, 02:18:43] [SwitchBot] [DEBUG] Curtain: Left Curtain OpenAPI parseStatus
[19/12/2021, 02:18:43] [SwitchBot] [DEBUG] Curtain Left Curtain CurrentPosition: 1
[19/12/2021, 02:18:43] [SwitchBot] Checking Left Curtain Status ...
[19/12/2021, 02:18:43] [SwitchBot] [DEBUG] Curtain: Left Curtain Standby, CurrentPosition: 1
[19/12/2021, 02:18:43] [SwitchBot] [DEBUG] Curtain: Left Curtain CurrentPosition: 1, TargetPosition: 0, PositionState: 0,
[19/12/2021, 02:18:43] [SwitchBot] [DEBUG] Curtain: Left Curtain CurrentAmbientLightLevel: 6001
[19/12/2021, 02:18:43] [SwitchBot] [DEBUG] Curtain: Left Curtain updateCharacteristic CurrentPosition: 1
[19/12/2021, 02:18:43] [SwitchBot] [DEBUG] Curtain: Left Curtain updateCharacteristic PositionState: 0
[19/12/2021, 02:18:43] [SwitchBot] [DEBUG] Curtain: Left Curtain updateCharacteristic TargetPosition: 0
[19/12/2021, 02:18:43] [SwitchBot] [DEBUG] Curtain: Left Curtain updateCharacteristic CurrentAmbientLightLevel: 6001
[19/12/2021, 02:18:43] [SwitchBot] [DEBUG] Curtain: Left Curtain Refresh Status When Moving, PositionState: 0
[19/12/2021, 02:18:43] [SwitchBot] [DEBUG] Curtain: Left Curtain OpenAPI refreshStatus
[19/12/2021, 02:18:43] [SwitchBot] [DEBUG] Curtain: Right Curtain refreshStatus: {"statusCode":100,"body":{"deviceId":"C5B51B79449C","deviceType":"Curtain","hubDeviceId":"E78C196D3920","calibrate":true,"group":false,"moving":false,"slidePosition":100},"message":"success"}
[19/12/2021, 02:18:43] [SwitchBot] [DEBUG] Curtain: Right Curtain OpenAPI parseStatus
[19/12/2021, 02:18:43] [SwitchBot] [DEBUG] Curtain Right Curtain CurrentPosition: 0
[19/12/2021, 02:18:43] [SwitchBot] Checking Right Curtain Status ...
[19/12/2021, 02:18:43] [SwitchBot] [DEBUG] Curtain: Right Curtain Standby, CurrentPosition: 0
[19/12/2021, 02:18:43] [SwitchBot] [DEBUG] Curtain: Right Curtain CurrentPosition: 0, TargetPosition: 0, PositionState: 0,
[19/12/2021, 02:18:43] [SwitchBot] [DEBUG] Curtain: Right Curtain CurrentAmbientLightLevel: 6001
[19/12/2021, 02:18:43] [SwitchBot] [DEBUG] Curtain: Right Curtain updateCharacteristic CurrentPosition: 0
[19/12/2021, 02:18:43] [SwitchBot] [DEBUG] Curtain: Right Curtain updateCharacteristic PositionState: 0
[19/12/2021, 02:18:43] [SwitchBot] [DEBUG] Curtain: Right Curtain updateCharacteristic TargetPosition: 0
[19/12/2021, 02:18:43] [SwitchBot] [DEBUG] Curtain: Right Curtain updateCharacteristic CurrentAmbientLightLevel: 6001
[19/12/2021, 02:18:43] [SwitchBot] [DEBUG] Curtain: Left Curtain refreshStatus: {"statusCode":100,"body":{"deviceId":"CD1BE5DAAB3A","deviceType":"Curtain","hubDeviceId":"E78C196D3920","calibrate":true,"group":false,"moving":false,"slidePosition":99},"message":"success"}
[19/12/2021, 02:18:43] [SwitchBot] [DEBUG] Curtain: Left Curtain OpenAPI parseStatus
[19/12/2021, 02:18:43] [SwitchBot] [DEBUG] Curtain Left Curtain CurrentPosition: 1
[19/12/2021, 02:18:43] [SwitchBot] Checking Left Curtain Status ...
[19/12/2021, 02:18:43] [SwitchBot] [DEBUG] Curtain: Left Curtain Standby, CurrentPosition: 1
[19/12/2021, 02:18:43] [SwitchBot] [DEBUG] Curtain: Left Curtain CurrentPosition: 1, TargetPosition: 0, PositionState: 0,
[19/12/2021, 02:18:43] [SwitchBot] [DEBUG] Curtain: Left Curtain CurrentAmbientLightLevel: 6001
[19/12/2021, 02:18:43] [SwitchBot] [DEBUG] Curtain: Left Curtain updateCharacteristic CurrentPosition: 1
[19/12/2021, 02:18:43] [SwitchBot] [DEBUG] Curtain: Left Curtain updateCharacteristic PositionState: 0
[19/12/2021, 02:18:43] [SwitchBot] [DEBUG] Curtain: Left Curtain updateCharacteristic TargetPosition: 0
[19/12/2021, 02:18:43] [SwitchBot] [DEBUG] Curtain: Left Curtain updateCharacteristic CurrentAmbientLightLevel: 6001
[19/12/2021, 02:18:46] [SwitchBot] [DEBUG] Curtain: Right Curtain setNewTarget true timeout
[19/12/2021, 02:18:46] [SwitchBot] [DEBUG] Curtain: Left Curtain setNewTarget true timeout
[19/12/2021, 02:18:48] [SwitchBot] [DEBUG] Curtain: Right Curtain Refresh Status When Moving, PositionState: 0
[19/12/2021, 02:18:48] [SwitchBot] [DEBUG] Curtain: Right Curtain OpenAPI refreshStatus
[19/12/2021, 02:18:48] [SwitchBot] [DEBUG] Curtain: Left Curtain Refresh Status When Moving, PositionState: 0
[19/12/2021, 02:18:48] [SwitchBot] [DEBUG] Curtain: Left Curtain OpenAPI refreshStatus
[19/12/2021, 02:18:48] [SwitchBot] [DEBUG] Curtain: Right Curtain refreshStatus: {"statusCode":100,"body":{"deviceId":"C5B51B79449C","deviceType":"Curtain","hubDeviceId":"E78C196D3920","calibrate":true,"group":false,"moving":false,"slidePosition":100},"message":"success"}
[19/12/2021, 02:18:48] [SwitchBot] [DEBUG] Curtain: Right Curtain OpenAPI parseStatus
[19/12/2021, 02:18:48] [SwitchBot] [DEBUG] Curtain Right Curtain CurrentPosition: 0
[19/12/2021, 02:18:48] [SwitchBot] [DEBUG] Curtain: Right Curtain Standby, CurrentPosition: 0
[19/12/2021, 02:18:48] [SwitchBot] [DEBUG] Curtain: Right Curtain CurrentPosition: 0, TargetPosition: 0, PositionState: 2,
[19/12/2021, 02:18:48] [SwitchBot] [DEBUG] Curtain: Right Curtain CurrentAmbientLightLevel: 6001
[19/12/2021, 02:18:48] [SwitchBot] [DEBUG] Curtain: Right Curtain updateCharacteristic CurrentPosition: 0
[19/12/2021, 02:18:48] [SwitchBot] [DEBUG] Curtain: Right Curtain updateCharacteristic PositionState: 2
[19/12/2021, 02:18:48] [SwitchBot] [DEBUG] Curtain: Right Curtain updateCharacteristic TargetPosition: 0
[19/12/2021, 02:18:48] [SwitchBot] [DEBUG] Curtain: Right Curtain updateCharacteristic CurrentAmbientLightLevel: 6001
[19/12/2021, 02:18:48] [SwitchBot] [DEBUG] Curtain: Left Curtain refreshStatus: {"statusCode":100,"body":{"deviceId":"CD1BE5DAAB3A","deviceType":"Curtain","hubDeviceId":"E78C196D3920","calibrate":true,"group":false,"moving":false,"slidePosition":100},"message":"success"}
[19/12/2021, 02:18:48] [SwitchBot] [DEBUG] Curtain: Left Curtain OpenAPI parseStatus
[19/12/2021, 02:18:48] [SwitchBot] [DEBUG] Curtain Left Curtain CurrentPosition: 0
[19/12/2021, 02:18:48] [SwitchBot] [DEBUG] Curtain: Left Curtain Standby, CurrentPosition: 0
[19/12/2021, 02:18:48] [SwitchBot] [DEBUG] Curtain: Left Curtain CurrentPosition: 0, TargetPosition: 0, PositionState: 2,
[19/12/2021, 02:18:48] [SwitchBot] [DEBUG] Curtain: Left Curtain CurrentAmbientLightLevel: 6001
[19/12/2021, 02:18:48] [SwitchBot] [DEBUG] Curtain: Left Curtain updateCharacteristic CurrentPosition: 0
[19/12/2021, 02:18:48] [SwitchBot] [DEBUG] Curtain: Left Curtain updateCharacteristic PositionState: 2
[19/12/2021, 02:18:48] [SwitchBot] [DEBUG] Curtain: Left Curtain updateCharacteristic TargetPosition: 0
[19/12/2021, 02:18:48] [SwitchBot] [DEBUG] Curtain: Left Curtain updateCharacteristic CurrentAmbientLightLevel: 6001
[19/12/2021, 02:19:19] [SwitchBot] [DEBUG] Bot: Bedroom Door OpenAPI refreshStatus
[19/12/2021, 02:19:20] [SwitchBot] [DEBUG] Curtain: Right Curtain OpenAPI refreshStatus
[19/12/2021, 02:19:20] [SwitchBot] [DEBUG] Curtain: Left Curtain OpenAPI refreshStatus
[19/12/2021, 02:19:20] [SwitchBot] [DEBUG] Bot: Bedroom Door refreshStatus: {"statusCode":100,"body":{"deviceId":"C465D0A162F0","deviceType":"Bot","hubDeviceId":"E78C196D3920","power":"off"},"message":"success"}
[19/12/2021, 02:19:20] [SwitchBot] [DEBUG] Bot: Bedroom Door OpenAPI parseStatus
[19/12/2021, 02:19:20] [SwitchBot] [DEBUG] Bot Bedroom Door On: false
[19/12/2021, 02:19:20] [SwitchBot] [DEBUG] Bot: Bedroom Door updateCharacteristic On: false
[19/12/2021, 02:19:20] [SwitchBot] [DEBUG] Curtain: Right Curtain refreshStatus: {"statusCode":100,"body":{"deviceId":"C5B51B79449C","deviceType":"Curtain","hubDeviceId":"E78C196D3920","calibrate":true,"group":false,"moving":false,"slidePosition":100},"message":"success"}
[19/12/2021, 02:19:20] [SwitchBot] [DEBUG] Curtain: Right Curtain OpenAPI parseStatus
[19/12/2021, 02:19:20] [SwitchBot] [DEBUG] Curtain Right Curtain CurrentPosition: 0
[19/12/2021, 02:19:20] [SwitchBot] [DEBUG] Curtain: Right Curtain Standby, CurrentPosition: 0
[19/12/2021, 02:19:20] [SwitchBot] [DEBUG] Curtain: Right Curtain CurrentPosition: 0, TargetPosition: 0, PositionState: 2,
[19/12/2021, 02:19:20] [SwitchBot] [DEBUG] Curtain: Right Curtain CurrentAmbientLightLevel: 6001
[19/12/2021, 02:19:20] [SwitchBot] [DEBUG] Curtain: Right Curtain updateCharacteristic CurrentPosition: 0
[19/12/2021, 02:19:20] [SwitchBot] [DEBUG] Curtain: Right Curtain updateCharacteristic PositionState: 2
[19/12/2021, 02:19:20] [SwitchBot] [DEBUG] Curtain: Right Curtain updateCharacteristic TargetPosition: 0
[19/12/2021, 02:19:20] [SwitchBot] [DEBUG] Curtain: Right Curtain updateCharacteristic CurrentAmbientLightLevel: 6001
[19/12/2021, 02:19:20] [SwitchBot] [DEBUG] Curtain: Left Curtain refreshStatus: {"statusCode":100,"body":{"deviceId":"CD1BE5DAAB3A","deviceType":"Curtain","hubDeviceId":"E78C196D3920","calibrate":true,"group":false,"moving":false,"slidePosition":100},"message":"success"}
[19/12/2021, 02:19:20] [SwitchBot] [DEBUG] Curtain: Left Curtain OpenAPI parseStatus
[19/12/2021, 02:19:20] [SwitchBot] [DEBUG] Curtain Left Curtain CurrentPosition: 0
[19/12/2021, 02:19:20] [SwitchBot] [DEBUG] Curtain: Left Curtain Standby, CurrentPosition: 0
[19/12/2021, 02:19:20] [SwitchBot] [DEBUG] Curtain: Left Curtain CurrentPosition: 0, TargetPosition: 0, PositionState: 2,
[19/12/2021, 02:19:20] [SwitchBot] [DEBUG] Curtain: Left Curtain CurrentAmbientLightLevel: 6001
[19/12/2021, 02:19:20] [SwitchBot] [DEBUG] Curtain: Left Curtain updateCharacteristic CurrentPosition: 0
[19/12/2021, 02:19:20] [SwitchBot] [DEBUG] Curtain: Left Curtain updateCharacteristic PositionState: 2
[19/12/2021, 02:19:20] [SwitchBot] [DEBUG] Curtain: Left Curtain updateCharacteristic TargetPosition: 0
[19/12/2021, 02:19:20] [SwitchBot] [DEBUG] Curtain: Left Curtain updateCharacteristic CurrentAmbientLightLevel: 6001
```

### Config for homebridge-switchbot

```shell
{
            "name": "SwitchBot",
            "credentials": {
                "openToken": "Redacted",
                "notice": "Keep your token a secret!"
            },
            "options": {
                "debug": "debug"
            },
            "platform": "SwitchBot"
        },
```

### Device & Model

Switchbot Curtain (newest model)

### Node.js Version

v14.18.2

### NPM Version

v6.14.15

### Homebridge Version

v1.3.8

### Homebridge Switchbot Plugin Version

v1.4.0

### Homebridge Config UI X Plugin Version

v4.41.5

### Operating System

Raspbian

**Comment by 618116** [comment] 2021-12-19 11:10
Does SwitchBot app show same 1%? If so, it is not a bug and due to your curtains physical tension.

**Comment by donavanbecker** [comment] 2021-12-19 12:05
@kylewhirl, @618116 is right, if your SwitchBot shows at all a little open, then that is what the API is showing. You can set the curtain min and max for each deviceid by inputting the deviceid of each of your curtains in the SwitchBot device settings and then putting like 10 and 90 and then the curtain will state that it is closed/open if it is 10 or lower or 90 or higher.

**Comment by kylewhirl** [comment] 2021-12-19 19:15
No. The switchbot app shows them as fully closed

**Comment by donavanbecker** [comment] 2021-12-19 19:58
@kylewhirl Did you set the min and max?

**Comment by kylewhirl** [comment] 2021-12-19 20:09
Yeah I set them. I can set them again to potentially fix the issue 

Kyle Worrall

**Comment by donavanbecker** [comment] 2021-12-27 06:22
Duplicate of #123

Closing, follow that issue for updates.

**Closed as completed by donavanbecker** 2021-12-27 06:22 UTC
Labels: bug, OpenAPI

**Comment by kylewhirl** [comment] 2022-01-01 20:51
> @kylewhirl, @618116 is right, if your SwitchBot shows at all a little open, then that is what the API is showing. You can set the curtain min and max for each deviceid by inputting the deviceid of each of your curtains in the SwitchBot device settings and then putting like 10 and 90 and then the curtain will state that it is closed/open if it is 10 or lower or 90 or higher.

How do I do this? At first I thought this was just recalibrating the switchbot but I understand it’s not now. Is this in the Homebridge config or switchbot app?
