### ISSUE TITLE
Bug: 403 forbidden messaged started today

### ISSUE THREAD

**Issue by Gordon-Newell** [OpenWonderLabs/homebridge-switchbot#1137] opened 2024-12-16 11:04 UTC
### Describe the Bug

Getting the following in the homebridge logs, everything was working fine yesterday

```
[16/12/2024, 09:50:42] [SwitchBot] Forbidden, The request has been authenticated but does not have appropriate permissions, or a requested resource is not found, 
            statusCode: 403
```
            
 Have reset my token in the switch bot app and updated it in hoebridge but the issue continues

### To Reproduce

Restarted homebridge and errors are appearing, actually just went wrong.

### Expected Behavior

Devices connect and operate in hombridge

### Relevant Log Output

```shell
[16/12/2024, 10:42:11] [SwitchBot] Initializing SwitchBot platform...
[16/12/2024, 10:42:13] [SwitchBot] [DEBUG] Using Platform Config Logging: debug
[16/12/2024, 10:42:13] [SwitchBot] [DEBUG] Using Platform Config refreshRate: 360
[16/12/2024, 10:42:13] [SwitchBot] [DEBUG] Platform Config: {"platform":"Resideo","logging":"debug","refreshRate":360}
[16/12/2024, 10:42:13] [SwitchBot] [DEBUG] Plugin Version: 4.1.5
[16/12/2024, 10:42:13] [SwitchBot] [DEBUG] Finished initializing platform: SwitchBot
[16/12/2024, 10:42:13] [SwitchBot] [DEBUG] Verifying Config
[16/12/2024, 10:42:13] [SwitchBot] [DEBUG] Config OK
[16/12/2024, 10:42:13] [SwitchBot] [DEBUG] Platform BLE is not enabled
[16/12/2024, 10:42:13] [SwitchBot] [DEBUG] Executed didFinishLaunching callback
[16/12/2024, 10:42:13] [SwitchBot] [DEBUG] Retry Count: 0
[16/12/2024, 10:42:13] [SwitchBot] [DEBUG] Max Retries: undefined
[16/12/2024, 10:42:13] [SwitchBot] [DEBUG] Delay Between Retries: undefined
[16/12/2024, 10:42:13] [SwitchBot] [DEBUG] Platform Config updateRate Not Set: undefined
Setup Payload:
X-HM://0024RBODHMEPK
                       
[16/12/2024, 10:42:13] [SwitchBot] [DEBUG] Platform Config pushRate Not Set: undefined
[16/12/2024, 10:42:13] [SwitchBot] [DEBUG] Platform Config maxRetries Not Set: undefined
[16/12/2024, 10:42:13] [SwitchBot] [DEBUG] Platform Config delayBetweenRetries Not Set: undefined
[16/12/2024, 10:42:13] Homebridge v1.8.5 (HAP v0.12.3) (Homebridge) is running on port 51826.
[16/12/2024, 10:42:13] 

NOTICE TO USERS AND PLUGIN DEVELOPERS
> Homebridge 2.0 is on the way and brings some breaking changes to existing plugins.
> Please visit the following link to learn more about the changes and how to prepare:
> https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0

[16/12/2024, 10:42:13] [SwitchBot] [DEBUG] Got devices: {"message":"Forbidden"}
[16/12/2024, 10:42:13] [SwitchBot] [DEBUG] statusCode: 403
[16/12/2024, 10:42:13] [SwitchBot] [DEBUG] response: {"message":"Forbidden"}
[16/12/2024, 10:42:13] [SwitchBot] Forbidden, The request has been authenticated but does not have appropriate permissions, or a requested resource is not found, 
            statusCode: 403
[16/12/2024, 10:42:14] [SwitchBot] [DEBUG] Got devices: {"message":"Forbidden"}
[16/12/2024, 10:42:14] [SwitchBot] [DEBUG] statusCode: 403
[16/12/2024, 10:42:14] [SwitchBot] [DEBUG] response: {"message":"Forbidden"}
[16/12/2024, 10:42:14] [SwitchBot] Forbidden, The request has been authenticated but does not have appropriate permissions, or a requested resource is not found, 
            statusCode: 403
[16/12/2024, 10:42:14] [SwitchBot] [DEBUG] Got devices: {"message":"Forbidden"}
[16/12/2024, 10:42:14] [SwitchBot] [DEBUG] statusCode: 403
[16/12/2024, 10:42:14] [SwitchBot] [DEBUG] response: {"message":"Forbidden"}
[16/12/2024, 10:42:14] [SwitchBot] Forbidden, The request has been authenticated but does not have appropriate permissions, or a requested resource is not found, 
            statusCode: 403
[16/12/2024, 10:42:14] [SwitchBot] [DEBUG] Got devices: {"message":"Forbidden"}
[16/12/2024, 10:42:14] [SwitchBot] [DEBUG] statusCode: 403
[16/12/2024, 10:42:14] [SwitchBot] [DEBUG] response: {"message":"Forbidden"}
[16/12/2024, 10:42:14] [SwitchBot] Forbidden, The request has been authenticated but does not have appropriate permissions, or a requested resource is not found, 
            statusCode: 403
[16/12/2024, 10:42:14] [SwitchBot] [DEBUG] Got devices: {"message":"Forbidden"}
[16/12/2024, 10:42:14] [SwitchBot] [DEBUG] statusCode: 403
[16/12/2024, 10:42:14] [SwitchBot] [DEBUG] response: {"message":"Forbidden"}
[16/12/2024, 10:42:14] [SwitchBot] Forbidden, The request has been authenticated but does not have appropriate permissions, or a requested resource is not found, 
            statusCode: 403
```

### Config for homebridge-switchbot

```shell
{
    "name": "SwitchBot",
    "credentials": {
        "token": "{blanked for privacy}",
        "secret": "{blanked for privacy}",
        "notice": "Keep your Token & Secret a secret!"
    },
    "options": {
        "refreshRate": 360,
        "logging": "debug"
    },
    "platform": "SwitchBot"
}
```

### Device and Model

Hub Mini v6.1-5.1, Switch bot curtains, K10 plus 

### Node.js Version

v22.12.0

### NPM Version

v10.9.2

### Homebridge Version

v1.8.5

### Homebridge Switchbot Plugin Version

v4.1.5

### Homebridge Config UI X Plugin Version

v4.65.1

### Operating System

Raspbian GNU/Linux Bullseye

**Comment by sw2719** [comment] 2024-12-16 13:43
Same issue here. It was working fine just few hours ago.

**Comment by felixtky** [comment] 2024-12-16 13:46
Same here

**Comment by nahive** [comment] 2024-12-16 13:59
https://github.com/OpenWonderLabs/SwitchBotAPI/issues/374
Just need an update with option to select hostname in case issues like those arise in the future.

**Comment by danny1605** [comment] 2024-12-16 16:43
Same issue here.

**Comment by MaxCodeDE** [comment] 2024-12-16 16:55
Same here with Hub Mini.

**Comment by ThisWill1992** [comment] 2024-12-16 17:14
Same here, all accessories same error since this morning. All worked fine went I went to bed, none working in the morning. Hub Mini.

**Comment by AdityaA1998** [comment] 2024-12-16 17:45
Same for me as well, hub mini and switchbot bot user.

**Comment by trolli-ch** [comment] 2024-12-16 18:34
+1 Hub mini + Switchbot Curtain

**Comment by th1rst** [comment] 2024-12-16 22:23
Same here

**Comment by mrtsrdrp** [comment] 2024-12-16 23:55
+1, hub mini, token reset, didn't fix

**Comment by donavanbecker** [comment] 2024-12-17 06:13
It looks like this has been resolved by SwitchBot. Since it has been asked in 4.1.6-beta.9 I have added an option to override the hostname.

Can you try the latest beta: 

[![npm version](https://badgen.net/badge/homebridge-switchbot@beta/>=4.1.6-beta.9/orange)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

[Click here to find out how to install Beta](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Beta-Version)

**Comment by arashjalalat** [comment] 2024-12-17 06:35
Now getting 401

**Comment by danny1605** [comment] 2024-12-17 06:36
> It looks like this has been resolved by SwitchBot. Since it has been asked in 4.1.6-beta.9 I have added an option to override the hostname.
> 
> Can you try the latest beta:
> 
> [![npm version](https://camo.githubusercontent.com/ede7cbf5fcec76c9e8ac19c08acdcec9020d912f188b37a26c89251468ab6ced/68747470733a2f2f62616467656e2e6e65742f62616467652f686f6d656272696467652d737769746368626f7440626574612f2533453d342e312e362d626574612e392f6f72616e6765)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)
> 
> [Click here to find out how to install Beta](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Beta-Version)

With this version everything works without errors

**Comment by donavanbecker** [comment] 2024-12-17 06:43
> Now getting 401

Probably not using the right hostname if you are overriding

**Closed as completed by donavanbecker** 2024-12-17 06:43 UTC
Labels: bug

**Comment by arashjalalat** [comment] 2024-12-17 06:53
> > Now getting 401
> 
> Probably not using the right hostname if you are overriding

Probably depends on region: https://github.com/OpenWonderLabs/SwitchBotAPI/issues/374#issuecomment-2547601168

**Comment by th1rst** [comment] 2024-12-17 08:13
Also switched to the latest beta, also getting 401 now instead of 403 (EU region)

**Comment by Gordon-Newell** [comment] 2024-12-17 09:24
This is working for me now, seems they have fixed it.  If anyone is still having issues, I suggest a restart of homebridge.

**Comment by felixtky** [comment] 2024-12-17 09:51
Getting an error code 401, despite SwitchBot saying the api issue is fixed.
I am living in Asia, not sure if the issue is regional.

**Comment by mrtsrdrp** [comment] 2024-12-17 20:58
403 was changed to 401, not using hostname override. EU. Everything on default.

**Comment by felixtky** [comment] 2024-12-18 03:20
seems that problem remains for users outside the US. issues not closed yet
