### ISSUE TITLE
Bug: Switchbot plugin started crashing Homebridge today 

### ISSUE THREAD

**Issue by nyjklein** [OpenWonderLabs/homebridge-switchbot#79] opened 2021-11-13 21:54 UTC
### Describe The Bug

Restarting Homebridge crashes when Switchbot plugin is configured 

### To Reproduce

Just restart. No changes to any of my SwitchBot devices or configuration have been made

### Expected behavior

Shouldn't crash!

### Relevant log output

```shell
[13/11/2021, 16:12:05] [SwitchBot] [DEBUG] {"statusCode":100,"body":{"deviceList":[{"deviceId":"98F4AB2F20EE","deviceName":"
Humidifier EE","deviceType":"Humidifier","enableCloudService":true,"hubDeviceId":"000000000000"},{"deviceId":"D8E9AA74909F","deviceName":"Li
ving Room Curtain Right","deviceType":"Curtain","hubDeviceId":"000000000000","curtainDevicesIds":["DFC80D28CE14","D8E9AA74909F"],"calibrate"
:true,"group":true,"master":false,"openDirection":"right"},{"deviceId":"DF7B6DA19FE7","deviceName":"Hub Mini E7","deviceType":"Hub Mini","hu
bDeviceId":"000000000000"},{"deviceId":"DFC80D28CE14","deviceName":"Living Room Curtain","deviceType":"Curtain","enableCloudService":true,"h
ubDeviceId":"DF7B6DA19FE7","curtainDevicesIds":["DFC80D28CE14","D8E9AA74909F"],"calibrate":true,"group":true,"master":true,"openDirection":"
left"},{"deviceId":"F037B7A5EED7","deviceName":"Bot D7","deviceType":"Bot","enableCloudService":true,"hubDeviceId":"DF7B6DA19FE7"},{"deviceI
d":"F1BAF4B4E58E","deviceName":"Living Room","deviceType":"Meter","enableCloudService":true,"hubDeviceId":"DF7B6DA19FE7"},{"deviceId":"F3745
EADBBFE","deviceName":"Bedroom","deviceType":"Meter","enableCloudService":true,"hubDeviceId":"DF7B6DA19FE7"}],"infraredRemoteList":[]},"mess
age":"success"}
[13/11/2021, 16:12:05] [SwitchBot] Total SwitchBot Devices Found: 7
[13/11/2021, 16:12:05] [SwitchBot] [DEBUG] SwitchBot Device Config Not Set: undefined
[13/11/2021, 16:12:05] [SwitchBot] [DEBUG] Discovered Humidifier: 98F4AB2F20EE
[13/11/2021, 16:12:05] [SwitchBot] Restoring existing accessory from cache: Humidifier EE DeviceID: 98F4AB2F20EE
[13/11/2021, 16:12:05] [SwitchBot] [DEBUG] Discovered Curtain: D8E9AA74909F
[13/11/2021, 16:12:05] [SwitchBot] [DEBUG] deviceId: D8E9AA74909F, curtainDevicesIds: DFC80D28CE14,D8E9AA74909F, master: fal
se, group: true, disable_group: undefined
[13/11/2021, 16:12:05] [SwitchBot] [DEBUG] [Curtain Config] disable_group: undefined
[13/11/2021, 16:12:05] [SwitchBot] [DEBUG] Discovered Hub Mini: DF7B6DA19FE7
[13/11/2021, 16:12:05] [SwitchBot] [DEBUG] Discovered Curtain: DFC80D28CE14
[13/11/2021, 16:12:05] [SwitchBot] [DEBUG] deviceId: DFC80D28CE14, curtainDevicesIds: DFC80D28CE14,D8E9AA74909F, master: tru
e, group: true, disable_group: undefined
[13/11/2021, 16:12:05] [SwitchBot] [DEBUG] [Curtain Config] disable_group: undefined
[13/11/2021, 16:12:05] [SwitchBot] Restoring existing accessory from cache: Living Room Curtain DeviceID: DFC80D28CE14
[13/11/2021, 16:12:05] [SwitchBot] [DEBUG] Discovered Bot: F037B7A5EED7
[13/11/2021, 16:12:05] [SwitchBot] Restoring existing accessory from cache: Bot D7 DeviceID: F037B7A5EED7
[13/11/2021, 16:12:05] [SwitchBot] [DEBUG] undefined
[13/11/2021, 16:12:05] [SwitchBot] You must set your Bot to Press or Switch Mode
[13/11/2021, 16:12:05] [SwitchBot] [DEBUG] Discovered Meter: F1BAF4B4E58E
[13/11/2021, 16:12:05] [SwitchBot] Restoring existing accessory from cache: Living Room DeviceID: F1BAF4B4E58E
[13/11/2021, 16:12:05] [SwitchBot] [DEBUG] Discovered Meter: F3745EADBBFE
[13/11/2021, 16:12:05] [SwitchBot] Restoring existing accessory from cache: Bedroom DeviceID: F3745EADBBFE
[13/11/2021, 16:12:05] [SwitchBot] Total IR Devices Found: 0
[13/11/2021, 16:12:05] [SwitchBot] [DEBUG] IR Device Config Not Set: undefined
[13/11/2021, 16:12:05] [SwitchBot] [DEBUG] Humidifier Humidifier EE CurrentTemperature: 0
[13/11/2021, 16:12:05] [SwitchBot] [DEBUG] Humidifier uuid: 98F4AB2F20EE-Humidifier, (179d92bf-d829-46ee-b45f-954e1a4e6bf1)
[13/11/2021, 16:12:05] [SwitchBot] [DEBUG] Curtain Living Room Curtain updateHomeKitCharacteristics - {"CurrentPosition":0,"
PositionState":2,"TargetPosition":0}
[13/11/2021, 16:12:05] [SwitchBot] [DEBUG] Curtain Living Room Curtain CurrentAmbientLightLevel: undefined
[13/11/2021, 16:12:05] [SwitchBot] [DEBUG] Curtain uuid: DFC80D28CE14-Curtain, (290ba6f5-8474-4a54-8d14-ce396a2e4251)
[13/11/2021, 16:12:05] [SwitchBot] [DEBUG] Bot Bot D7 On: false
[13/11/2021, 16:12:05] [SwitchBot] Bot Bot D7 failed to refresh status, Error Message: "Cannot read properties of undefi
ned (reading 'updateCharacteristic')"
[13/11/2021, 16:12:05] [SwitchBot] [DEBUG] Bot Bot D7, Error: {}
[13/11/2021, 16:12:05] [SwitchBot] [DEBUG] Bot Bot D7 BatteryLevel: undefined
[13/11/2021, 16:12:05] [SwitchBot] [DEBUG] Bot Bot D7 StatusLowBattery: undefined
[13/11/2021, 16:12:05] [SwitchBot] [DEBUG] Bot uuid: F037B7A5EED7-Bot, (cffc0071-664c-4055-b95d-fc427c34c3a8)
[13/11/2021, 16:12:05] [SwitchBot] [DEBUG] Meter uuid: F1BAF4B4E58E-Meter, (c79c02a1-a3a0-4f6f-ac00-41124aa94a2a)
[13/11/2021, 16:12:05] [SwitchBot] [DEBUG] Meter uuid: F3745EADBBFE-Meter, (97065854-0ef6-426d-9a6f-5604eb4076d8)
[13/11/2021, 16:12:05] TypeError: Cannot read properties of undefined (reading 'updateCharacteristic')
    at Bot.apiError (/usr/local/lib/node_modules/@switchbot/homebridge-switchbot/src/devices/bots.ts:356:18)
    at Bot.openAPIRefreshStatus (/usr/local/lib/node_modules/@switchbot/homebridge-switchbot/src/devices/bots.ts:233:12)
    at Bot.refreshStatus (/usr/local/lib/node_modules/@switchbot/homebridge-switchbot/src/devices/bots.ts:168:18)
    at new Bot (/usr/local/lib/node_modules/@switchbot/homebridge-switchbot/src/devices/bots.ts:52:10)
    at SwitchBotPlatform.createBot (/usr/local/lib/node_modules/@switchbot/homebridge-switchbot/src/platform.ts:440:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[13/11/2021, 16:12:05] Got SIGTERM, shutting down Homebridge...
```

### Config for homebridge-switchbot

```shell
"name": "SwitchBot",
            "credentials": {
                "openToken": "secret",
                "notice": "Keep your token a secret!"
            },
            "options": {
                "refreshRate": 600,
                "debug": "debug"
            },
            "platform": "SwitchBot"
        },
```

### Screenshots

None

### Device & Model

N/A

### Node.js Version

v16.13.0

### NPM Version

v8.1.0

### Homebridge Version

v1.3.6

### Homebridge Switchbot Plugin Version

v1.0.0

### Homebridge Config UI X Plugin Version

v4.41.2

### Operating System

Raspbian

**Comment by nfsilva999** [comment] 2021-11-14 11:38
Same error here. 
I just update for the new version of the Switch bot plugin and crash my homebridge instance.
![Captura de ecrã 2021-11-14, às 11 37 55](https://user-images.githubusercontent.com/655453/141679225-1d31cec1-0b7e-49dd-9e95-9a06f2483e4c.png)

**Comment by donavanbecker** [comment] 2021-11-14 14:10
duplicate of #77

**Comment by deflao** [comment] 2021-11-15 04:07
I'm still having the same issue even when updated to v1.0.1

**Comment by donavanbecker** [comment] 2021-11-15 04:17
@deflao Please open a new issue, and post logs because more then likely it is a different issue.

**Closed as completed** 2021-11-15 04:17 UTC
Labels: bug
