### ISSUE TITLE
Bug: bot doesn’t show up in BLE mode

### ISSUE THREAD

**Issue by adamrzanek** [OpenWonderLabs/homebridge-switchbot#80] opened 2021-11-14 09:55 UTC
### Describe The Bug

I think I’m doing everything right but bot doesn’t show up

### To Reproduce

Trying to config it

### Expected behavior

Bot should show up

### Relevant log output

```shell
I’ve made screenshot since I’m on my phone and can’t copy. I’ve added screenshots from other plugin also
```

### Config for homebridge-switchbot

```shell
{
            "name": "SwitchBot",
            "credentials": {
                "openToken": "Secret",
                "notice": "Keep your token a secret!"
            },
            "options": {
                "devices": [
                    {
                        "deviceId": "Secret",
                        "deviceType": "Bot",
                        "ble": true,
                        "bot": {
                            "mode": "press",
                            "switch": true
                        }
                    }
                ],
                "debug": "device"
            },
            "platform": "SwitchBot"
        }
```

### Screenshots
<a><img src="https://user-images.githubusercontent.com/65444919/141675880-0e4c256e-5e15-4456-9148-a736340a312e.png" width="250px"></a>
<a><img src="https://user-images.githubusercontent.com/65444919/141675881-1a0c9294-4d46-4b50-a62d-8dc4c4e59497.png" width="250px"></a>
<a><img src="https://user-images.githubusercontent.com/65444919/141676175-d98b9d62-c777-4ae0-8d5c-1f1248d5a2a1.png" width="250px"></a>

### Device & Model

Switchbot bot

### Node.js Version

V16.13.0

### NPM Version

V8.1.0

### Homebridge Version

V1.3.6

### Homebridge Switchbot Plugin Version

1.0

### Homebridge Config UI X Plugin Version

4.41.2

### Operating System

Rasbian

**Comment by donavanbecker** [comment] 2021-11-14 14:10
duplicate of #77

**Closed as completed** 2021-11-14 14:12 UTC
Labels: bug
