### ISSUE TITLE
Bug: SwitchBot not working with BLE and keep rebooting the child bridge

### ISSUE THREAD

**Issue by morning3tar** [OpenWonderLabs/homebridge-switchbot#977] opened 2024-05-27 13:38 UTC
### Describe the Bug

Hello, I am experiencing an issue with the plugin when attempting to use the bot in BLE mode. The plugin is not working correctly and keeps causing the child bridge to reboot.

### To Reproduce

1. Install Homebridge on a Raspberry Pi.
2. Install the plugin.
3. Configure the plugin to use BLE mode.

### Expected Behavior

The plugin should be able to control the SwitchBot devices in BLE mode without causing the child bridge to reboot.

### Relevant Log Output

```shell
[27/05/2024, 09:24:58] [SwitchBot] [DEBUG] Bot: SwitchBot Max Retries Not Set, Using: 5
[27/05/2024, 09:24:58] [SwitchBot] [DEBUG] Bot: SwitchBot Delay Between Retries Not Set, Using: 3000
[27/05/2024, 09:24:58] [SwitchBot] [DEBUG] Bot: SwitchBot Config: {"logging":"debug","scanDuration":10,"maxRetry":7,"connectionType":"BLE","mode":"switch","deviceType":"switch","allowPush":true,"doublePress":1}
[27/05/2024, 09:24:58] [SwitchBot] [DEBUG] Bot: SwitchBot Model: SwitchBot S1, BLE Model: H
[27/05/2024, 09:24:58] [SwitchBot] [DEBUG] Bot: SwitchBot 3 FirmwareRevision: 3.5.0
[27/05/2024, 09:24:58] [SwitchBot] [DEBUG] Bot: SwitchBot Firmware Version: 3.5.0
[27/05/2024, 09:24:58] [SwitchBot] [DEBUG] Bot: SwitchBot deviceVersion: 3.5.0
[27/05/2024, 09:24:58] [SwitchBot] [DEBUG] Bot: SwitchBot Using Device Config scanDuration: 10
[27/05/2024, 09:24:58] [SwitchBot] [DEBUG] Bot: SwitchBot Accessory Cache: switch
[27/05/2024, 09:24:58] [SwitchBot] [DEBUG] Bot: SwitchBot Using Device Type: switch
[27/05/2024, 09:24:58] [SwitchBot] [DEBUG] Bot: SwitchBot Using Bot Mode: switch
[27/05/2024, 09:24:58] [SwitchBot] [DEBUG] Bot: SwitchBot Using Default Bot pushRatePress: 15
[27/05/2024, 09:24:58] [SwitchBot] [DEBUG] Bot: SwitchBot Allowing Push Changes: true
[27/05/2024, 09:24:58] [SwitchBot] [DEBUG] Bot: SwitchBot Displaying as Switch
[27/05/2024, 09:24:58] [SwitchBot] [DEBUG] Bot: SwitchBot BLERefreshStatus
[27/05/2024, 09:24:58] [SwitchBot] [DEBUG] Bot: SwitchBot updateCharacteristic On: false
[27/05/2024, 09:24:58] [SwitchBot] [DEBUG] Bot: SwitchBot is not listening webhook.
[27/05/2024, 09:24:58] [SwitchBot] [DEBUG] Bot: SwitchBot updateCharacteristic BatteryLevel: 100
[27/05/2024, 09:24:58] [SwitchBot] [DEBUG] Bot: SwitchBot updateCharacteristic StatusLowBattery: 0
[27/05/2024, 09:24:58] [SwitchBot] [DEBUG] Bot: SwitchBot BLE Address: d3:35:xx:xx:xx:xx
[27/05/2024, 09:25:02] [SwitchBot] Bot: SwitchBot Set ProgrammableSwitchOutputState: true
[27/05/2024, 09:25:02] [SwitchBot] [DEBUG] Bot: SwitchBot BLEpushChanges
[27/05/2024, 09:25:02] [SwitchBot] [DEBUG] Bot: SwitchBot BLEpushChanges On: true OnCached: false
[27/05/2024, 09:25:02] [SwitchBot] [DEBUG] Bot: SwitchBot BLE Address: d3:35:xx:xx:xx:xx
[27/05/2024, 09:25:02] [SwitchBot] [DEBUG] Bot: SwitchBot Press Mode: switch
[27/05/2024, 09:25:07] [SwitchBot] Bot: SwitchBot On: true
[27/05/2024, 09:25:07] [SwitchBot] TypeError: Cannot read properties of undefined (reading 'turnOn')
[27/05/2024, 09:25:07] [SwitchBot] Bot: SwitchBot Retrying
[27/05/2024, 09:25:08] [SwitchBot] [DEBUG] Bot: SwitchBot BLEparseStatus
TypeError: Cannot read properties of undefined (reading 'mode')
    at Bot.BLEparseStatus (file:///var/lib/homebridge/node_modules/@switchbot/homebridge-switchbot/src/device/bot.ts:510:21)
    at file:///var/lib/homebridge/node_modules/@switchbot/homebridge-switchbot/src/device/bot.ts:629:18
[27/05/2024, 09:25:08] [SwitchBot] Child bridge process ended
[27/05/2024, 09:25:08] [SwitchBot] Process Ended. Code: 1, Signal: null
[27/05/2024, 09:25:15] [SwitchBot] Restarting Process...
```

### Config for homebridge-switchbot

```shell
{
    "name": "SwitchBot",
    "credentials": {
        "token": "xxxx",
        "secret": "xxxx",
        "notice": "Keep your Token & Secret a secret!"
    },
    "options": {
        "devices": [
            {
                "deviceId": "D3:35:xx:xx:xx:xx",
                "configDeviceName": "SwitchBot",
                "configDeviceType": "Bot",
                "connectionType": "BLE",
                "scanDuration": 10,
                "bot": {
                    "mode": "switch",
                    "deviceType": "switch",
                    "allowPush": true,
                    "doublePress": 1
                },
                "maxRetry": 7,
                "logging": "debug"
            }
        ]
    },
    "_bridge": {
        "username": "0E:xx:xx:xx:xx:xx",
        "port": 550xx
    },
    "platform": "SwitchBot"
}
```

### Device and Model

SwitchBot V6.6

### Node.js Version

v20.13.1

### NPM Version

v8.19.4

### Homebridge Version

v1.8.2

### Homebridge Switchbot Plugin Version

v3.5.0

### Operating System

Raspbian

**Comment by donavanbecker** [comment] 2024-05-27 13:57
Did this work for you on previous versions?

**Comment by badxhabit** [comment] 2024-05-27 17:35
Getting the same issue. I disabled the Switchbot plugin and everything is working now.

**Comment by Boscosticks** [comment] 2024-05-27 18:09
+1 Same issue here. 

I rolled back 3.4.0, and everything is working as intended.

**Comment by donavanbecker** [comment] 2024-05-27 18:46
And is this only on Bots for everyone?

**Comment by Boscosticks** [comment] 2024-05-27 19:08
> And is this only on Bots for everyone?

Yep. I have the same error message as OP.

**Comment by morning3tar** [comment] 2024-05-27 23:48
> +1 Same issue here.
> 
> I rolled back 3.4.0, and everything is working as intended.

I rolled back to the 3.4.0 version but the issue persists and not working.

**Comment by donavanbecker** [comment] 2024-05-28 11:57
I have found part of the issue, just need to figure out a fix and resolve it. I will do it as quick as I can as life allows.

**Comment by CalamandreiLorenzo** [comment] 2024-06-04 21:48
Hi, idk if can be of any help, I think the error is also present for hubs, or at least I have a similar error for the humidity retrieving of hub2, the error message seems the same, so it could be related.

```
TypeError: Cannot read properties of undefined (reading 'CurrentRelativeHumidity') 
at Hub.updateHomeKitCharacteristics (file:///homebridge/node_modules/@switchbot/homebridge-switchbot/src/device/hub.ts: 345:37)
at new Hub (file:///homebridge/node_modules/@switchbot/homebridge-switchbot/src/device/hub.ts:141:10)
at SwitchBotPlatform.createHub2 (file:///homebridge/node_modules/@switchbot/homebridge-switchbot/src/platform.ts: 1094:9)
at processTicksAndRejections (node: internal/process/task_queues: 95:5)
```

**Comment by teh-hippo** [comment] 2024-06-05 02:18
Similar issue as above.  Fixed by reverting the version.

```
[05/06/2024, 12:17:10 pm] [SwitchBot] Restoring existing accessory from cache: Hub 2 DeviceID: ABC123
TypeError: Cannot read properties of undefined (reading 'battery')
    at Meter.BLEparseStatus (file:///var/lib/homebridge/node_modules/@switchbot/homebridge-switchbot/src/device/meter.ts:155:52)
    at file:///var/lib/homebridge/node_modules/@switchbot/homebridge-switchbot/src/device/meter.ts:267:18
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:540:9)
    at processTimers (node:internal/timers:514:7)
```

**Comment by teh-hippo** [comment] 2024-06-20 22:50
I don't believe this is stale; I'm still on 3.4.
In case it helps, I'm running on a Raspberry Pi.

```
[21/06/2024, 8:49:41 am] [SwitchBot] Restoring existing accessory from cache: Hub 2 DeviceID: MY_DEVICE_ID
TypeError: Cannot read properties of undefined (reading 'battery')
    at Meter.BLEparseStatus (file:///var/lib/homebridge/node_modules/@switchbot/homebridge-switchbot/src/device/meter.ts:155:52)
    at file:///var/lib/homebridge/node_modules/@switchbot/homebridge-switchbot/src/device/meter.ts:267:18
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:540:9)
    at processTimers (node:internal/timers:514:7)
[21/06/2024, 8:49:47 am] [SwitchBot] Child bridge process ended
```

**Comment by donavanbecker** [comment] 2024-06-21 03:53
> I don't believe this is stale; I'm still on 3.4. In case it helps, I'm running on a Raspberry Pi.
> 
> ```
> [21/06/2024, 8:49:41 am] [SwitchBot] Restoring existing accessory from cache: Hub 2 DeviceID: MY_DEVICE_ID
> TypeError: Cannot read properties of undefined (reading 'battery')
>     at Meter.BLEparseStatus (file:///var/lib/homebridge/node_modules/@switchbot/homebridge-switchbot/src/device/meter.ts:155:52)
>     at file:///var/lib/homebridge/node_modules/@switchbot/homebridge-switchbot/src/device/meter.ts:267:18
>     at runNextTicks (node:internal/process/task_queues:60:5)
>     at listOnTimeout (node:internal/timers:540:9)
>     at processTimers (node:internal/timers:514:7)
> [21/06/2024, 8:49:47 am] [SwitchBot] Child bridge process ended
> ```

can you try the latest beta?

**Comment by teh-hippo** [comment] 2024-06-21 06:52
Issue is still occurring.

```
[21/06/2024, 4:48:10 pm] [SwitchBot] MeterPlus: Server Meter ad: {
  "id": "ab1c234567d8",
  "address": "ab:1c:23:45:67:d8",
  "rssi": -32,
  "serviceData": {
    "model": "i",
    "modelName": "WoSensorTH",
    "modelfriendlyName": "Meter",
    "temperature": {
      "c": 18.6,
      "f": 65.5
    },
    "fahrenheit": false,
    "humidity": 51,
    "battery": 100
  }
}
[21/06/2024, 4:48:12 pm] [SwitchBot] MeterPlus: Server Meter ad: {
  "id": "ab1c234567d8",
  "address": "ab:1c:23:45:67:d8",
  "rssi": -27,
  "serviceData": {
    "model": "i",
    "modelName": "WoSensorTH",
    "modelfriendlyName": "Meter",
    "temperature": {
      "c": 18.6,
      "f": 65.5
    },
    "fahrenheit": false,
    "humidity": 51,
    "battery": 100
  }
}
[21/06/2024, 4:48:14 pm] [SwitchBot] MeterPlus: Server Meter ad: {
  "id": "ab1c234567d8",
  "address": "ab:1c:23:45:67:d8",
  "rssi": -28,
  "serviceData": {
    "model": "i",
    "modelName": "WoSensorTH",
    "modelfriendlyName": "Meter",
    "temperature": {
      "c": 18.6,
      "f": 65.5
    },
    "fahrenheit": false,
    "humidity": 51,
    "battery": 100
  }
}
TypeError: Cannot read properties of undefined (reading 'c')
    at Meter.BLEparseStatus (file:///var/lib/homebridge/node_modules/@switchbot/homebridge-switchbot/src/device/meter.ts:164:47)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:540:9)
    at processTimers (node:internal/timers:514:7)
    at file:///var/lib/homebridge/node_modules/@switchbot/homebridge-switchbot/src/device/meter.ts:263:11
[21/06/2024, 4:48:15 pm] [SwitchBot] Child bridge process ended
```

**Comment by donavanbecker** [comment] 2024-06-28 02:45
v3.5.1 has been released, please install and let me know if this has been resolved.

**Comment by teh-hippo** [comment] 2024-06-28 07:41
Negative; same problem.

**Comment by morning3tar** [comment] 2024-07-01 14:23
Still have some issues.
`[01/07/2024, 10:22:15] [SwitchBot] Child bridge process ended
[01/07/2024, 10:22:15] [SwitchBot] Process Ended. Code: 1, Signal: null
[01/07/2024, 10:22:22] [SwitchBot] Restarting Process...
[01/07/2024, 10:22:22] [SwitchBot] Launched child bridge with PID 3737
[01/07/2024, 10:22:23] Registering platform '@switchbot/homebridge-switchbot.SwitchBot'
[01/07/2024, 10:22:23] [SwitchBot] Loaded @switchbot/homebridge-switchbot v3.5.1 child bridge successfully
[01/07/2024, 10:22:23] Loaded 1 cached accessories from cachedAccessories.0E64A761D43C.
[01/07/2024, 10:22:23] Homebridge v1.8.3 (HAP v0.12.2) (SwitchBot) is running on port 32335.
[01/07/2024, 10:22:24] [SwitchBot] Total SwitchBot Devices Found: 1
[01/07/2024, 10:22:24] [SwitchBot] Restoring existing accessory from cache: SwitchBot deviceId: D3353334596B
[01/07/2024, 10:22:29] [SwitchBot] Bot: SwitchBot failed to get serviceData, serviceData: [object Object]
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Timeout'
    |     property '_idlePrev' -> object with constructor 'TimersList'
    --- property '_idleNext' closes the circle
    at JSON.stringify (<anonymous>)
    at Bot.BLERefreshConnection (file:///var/lib/homebridge/node_modules/@switchbot/homebridge-switchbot/src/device/bot.ts:1392:90)
    at file:///var/lib/homebridge/node_modules/@switchbot/homebridge-switchbot/src/device/bot.ts:680:22
[01/07/2024, 10:22:29] [SwitchBot] Child bridge process ended
[01/07/2024, 10:22:29] [SwitchBot] Process Ended. Code: 1, Signal: null
[01/07/2024, 10:22:36] [SwitchBot] Restarting Process...`

**Comment by morning3tar** [comment] 2024-07-01 14:28
Still have some issues.

```[01/07/2024, 10:22:15] [SwitchBot] Child bridge process ended
[01/07/2024, 10:22:15] [SwitchBot] Process Ended. Code: 1, Signal: null
[01/07/2024, 10:22:22] [SwitchBot] Restarting Process...
[01/07/2024, 10:22:22] [SwitchBot] Launched child bridge with PID 3737
[01/07/2024, 10:22:23] Registering platform '@switchbot/homebridge-switchbot.SwitchBot'
[01/07/2024, 10:22:23] [SwitchBot] Loaded @switchbot/homebridge-switchbot v3.5.1 child bridge successfully
[01/07/2024, 10:22:23] Loaded 1 cached accessories from cachedAccessories.0xx4xxxxD43x.
[01/07/2024, 10:22:23] Homebridge v1.8.3 (HAP v0.12.2) (SwitchBot) is running on port 32125.
[01/07/2024, 10:22:24] [SwitchBot] Total SwitchBot Devices Found: 1
[01/07/2024, 10:22:24] [SwitchBot] Restoring existing accessory from cache: SwitchBot deviceId: Dxx533xxxxxx
[01/07/2024, 10:22:29] [SwitchBot] Bot: SwitchBot failed to get serviceData, serviceData: [object Object]
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Timeout'
    |     property '_idlePrev' -> object with constructor 'TimersList'
    --- property '_idleNext' closes the circle
    at JSON.stringify (<anonymous>)
    at Bot.BLERefreshConnection (file:///var/lib/homebridge/node_modules/@switchbot/homebridge-switchbot/src/device/bot.ts:1392:90)
    at file:///var/lib/homebridge/node_modules/@switchbot/homebridge-switchbot/src/device/bot.ts:680:22
[01/07/2024, 10:22:29] [SwitchBot] Child bridge process ended
[01/07/2024, 10:22:29] [SwitchBot] Process Ended. Code: 1, Signal: null
[01/07/2024, 10:22:36] [SwitchBot] Restarting Process...
```

**Comment by donavanbecker** [comment] 2024-07-05 14:14
Can you try the latest beta: 

[![npm version](https://badgen.net/badge/homebridge-switchbot@beta/>=3.5.2-beta.4/orange)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

[Click here to find out how to install Beta](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Beta-Version)

**Comment by morning3tar** [comment] 2024-07-06 12:20
> Can you try the latest beta:
> 
> [![npm version](https://camo.githubusercontent.com/ef04ca1d77c1fae253f8457f7b7add75507cc253fdd6b10737a44530fd972088/68747470733a2f2f62616467656e2e6e65742f62616467652f686f6d656272696467652d737769746368626f7440626574612f2533453d332e352e322d626574612e342f6f72616e6765)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)
> 
> [Click here to find out how to install Beta](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Beta-Version)

Still not working:
```Total SwitchBot Devices Found: 1
[06/07/2024, 08:16:45] [SwitchBot] Restoring existing accessory from cache: SwitchBot deviceId: xxxxxx3xxxxx
[06/07/2024, 08:16:45] [SwitchBot] Bot: SwitchBot scanDuration is less than updateRate, overriding scanDuration with updateRate
[06/07/2024, 08:16:45] [SwitchBot] Bot: SwitchBot Removing any leftover Fan Service
[06/07/2024, 08:16:45] [SwitchBot] Bot: SwitchBot Removing any leftover Lock Service
[06/07/2024, 08:16:45] [SwitchBot] Bot: SwitchBot Removing any leftover Door Service
[06/07/2024, 08:16:45] [SwitchBot] Bot: SwitchBot Removing any leftover Faucet Service
[06/07/2024, 08:16:45] [SwitchBot] Bot: SwitchBot Removing any leftover Outlet Service
[06/07/2024, 08:16:45] [SwitchBot] Bot: SwitchBot Removing any leftover Window Service
[06/07/2024, 08:16:45] [SwitchBot] Bot: SwitchBot Removing any leftover Garage Door Service
[06/07/2024, 08:16:45] [SwitchBot] Bot: SwitchBot Removing any leftover Window Covering Service
[06/07/2024, 08:16:45] [SwitchBot] Bot: SwitchBot Removing any leftover Stateful Programmable Switch Service
[06/07/2024, 08:16:59] [SwitchBot] Bot: SwitchBot On: true
[06/07/2024, 08:16:59] [SwitchBot] Bot: SwitchBot TypeError: Cannot read properties of undefined (reading 'turnOn')
[06/07/2024, 08:16:59] [SwitchBot] Bot: SwitchBot Retrying
[06/07/2024, 08:17:00] [SwitchBot] Bot: SwitchBot TypeError: Cannot read properties of undefined (reading 'turnOn')
[06/07/2024, 08:17:00] [SwitchBot] Bot: SwitchBot Retrying
[06/07/2024, 08:17:01] [SwitchBot] Bot: SwitchBot TypeError: Cannot read properties of undefined (reading 'turnOn')
[06/07/2024, 08:17:01] [SwitchBot] Bot: SwitchBot Retrying
[06/07/2024, 08:17:02] [SwitchBot] Bot: SwitchBot TypeError: Cannot read properties of undefined (reading 'turnOn')
[06/07/2024, 08:17:02] [SwitchBot] Bot: SwitchBot Retrying
[06/07/2024, 08:17:03] [SwitchBot] Bot: SwitchBot TypeError: Cannot read properties of undefined (reading 'turnOn')
[06/07/2024, 08:17:03] [SwitchBot] Bot: SwitchBot Retrying
[06/07/2024, 08:17:04] [SwitchBot] Bot: SwitchBot failed BLEpushChanges with BLE Connection, Error Message: "Cannot read properties of undefined (reading 'turnOn')"
```

**Comment by michaelgroening** [comment] 2024-07-06 21:35
same here… still not working. the plugin seems to loose it when a configured device is not reachable. the reboot loop seems to stop once the connection is stable. at least that happened as soon as every device was connected successfully. after I connected a hard to reach device with a low signal the reboot loops came back.

**Comment by donavanbecker** [comment] 2024-07-13 06:26
Can you try the latest beta: 

[![npm version](https://badgen.net/badge/homebridge-switchbot@beta/>=3.6.1-beta.2/orange)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

[Click here to find out how to install Beta](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Beta-Version)

**Comment by teh-hippo** [comment] 2024-07-13 06:33
Negative

**Comment by Boscosticks** [comment] 2024-07-15 21:07
I installed latest (3.6.0), and everything is working. Thank you!

**Comment by teh-hippo** [comment] 2024-07-16 12:43
I’m still having issues on 3.6.0.

TypeError: Cannot read properties of undefined (reading 'c')
    at Meter.BLEparseStatus
***@***.***/homebridge-switchbot/src/device/meter.ts:168:127)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:540:9)
    at processTimers (node:internal/timers:514:7)
    at ***@***.***/homebridge-switchbot/src/device/meter.ts:292:11

**Comment by emJay90** [comment] 2024-07-27 05:30
Still Rebooting at 3.7.0

`[27/07/2024, 07:29:57] [SwitchBot] MeterPlus: MeterPlus failed to get serviceData, serviceData: [object Object]
[27/07/2024, 07:29:57] [SwitchBot] MeterPlus: MeterPlus wasn't able to establish BLE Connection, node-switchbot: [object Object]
[27/07/2024, 07:29:57] TypeError: Cannot use 'in' operator to search for 'power' in undefined
    at FakeGatoHistory.addEntry (/var/lib/homebridge/node_modules/@switchbot/homebridge-switchbot/node_modules/fakegato-history/fakegato-history.js:542:22)
    at Curtain.updateCharacteristic (file:///var/lib/homebridge/node_modules/@switchbot/homebridge-switchbot/src/device/device.ts:436:30)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:545:9)
    at processTimers (node:internal/timers:519:7)
    at Curtain.updateHomeKitCharacteristics (file:///var/lib/homebridge/node_modules/@switchbot/homebridge-switchbot/src/device/curtain.ts:688:5)
    at file:///var/lib/homebridge/node_modules/@switchbot/homebridge-switchbot/src/device/curtain.ts:469:13
[27/07/2024, 07:29:57] TypeError: Cannot use 'in' operator to search for 'power' in undefined
    at FakeGatoHistory.addEntry (/var/lib/homebridge/node_modules/@switchbot/homebridge-switchbot/node_modules/fakegato-history/fakegato-history.js:542:22)
    at Curtain.updateCharacteristic (file:///var/lib/homebridge/node_modules/@switchbot/homebridge-switchbot/src/device/device.ts:436:30)
    at Curtain.updateHomeKitCharacteristics (file:///var/lib/homebridge/node_modules/@switchbot/homebridge-switchbot/src/device/curtain.ts:688:5)
    at file:///var/lib/homebridge/node_modules/@switchbot/homebridge-switchbot/src/device/curtain.ts:469:13
[27/07/2024, 07:29:57] Got SIGTERM, shutting down Homebridge...`


Best,
emJay

**Comment by donavanbecker** [comment] 2024-09-10 21:36
Can you try the latest beta: 

[![npm version](https://badgen.net/badge/homebridge-switchbot@beta/>=3.7.1-beta.19/orange)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

[Click here to find out how to install Beta](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Beta-Version)

**Comment by teh-hippo** [comment] 2024-09-10 21:52
Negative unfortunately. Same error as before.
Will revert to 3.4.0 again.
Version tried: 3.7.1 beta.19

**Comment by donavanbecker** [comment] 2024-09-11 09:53
can you pleas get me the latest logs?

**Comment by teh-hippo** [comment] 2024-09-13 01:51
I've tried on 3.8.0 and got the following:

```
TypeError: Cannot read properties of undefined (reading 'c')
    at Meter.BLEparseStatus (file:///var/lib/homebridge/node_modules/@switchbot/homebridge-switchbot/src/device/meter.ts:176:127)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:545:9)
    at processTimers (node:internal/timers:519:7)
    at file:///var/lib/homebridge/node_modules/@switchbot/homebridge-switchbot/src/device/meter.ts:294:11
```

**Comment by teh-hippo** [comment] 2024-09-13 01:54
I've tried using 3.8.1, and so far it appears to be working!

**Closed as completed** 2024-09-14 08:21 UTC
Labels: bug
