### ISSUE TITLE
Support Request: fail to use accessories

### ISSUE THREAD

**Issue by jaaaaaaasonw** [OpenWonderLabs/homebridge-switchbot#1138] opened 2024-12-16 14:51 UTC
### Describe Your Problem

sudden connection failure 

### Relevant log output

```shell
came home today and fall to use accessories at home.
getting error in home bridge log like this
[SwitchBot] Forbidden, The request has been authenticated but does not have appropriate permissions, or a requested resource is not found, 
            statusCode: 403
tried re-logging and even re-installing switchbot plugin. did not work
please help
```

### Config for homebridge-switchbot

```shell
{
    "name": "SwitchBot",
    "credentials": {
        "token": "***",
        "secret": "***",
        "notice": "Keep your Token & Secret a secret!"
    },
    "_bridge": {
        "username": "0E:54:5A:BB:26:87",
        "port": 59085
    },
    "platform": "SwitchBot"
}
```

### Device & Model

Mac mini 2018 Sonoma 14.5

### Node.js Version

v20.16.0

### NPM Version

v10.8.1

### Homebridge Version

v1.8.5

### Homebridge SwitchBot Plugin Version

v4.1.5

### Operating System

macOS

**Comment by Gordon-Newell** [comment] 2024-12-16 15:06
This is a duplicate of #1137

**Closed as completed** 2024-12-17 06:35 UTC
Labels: question
