### ISSUE TITLE
Support Request: SwitchBot status changes to ON automatically

### ISSUE THREAD

**Issue by tzwada** [OpenWonderLabs/homebridge-switchbot#105] opened 2021-11-22 01:17 UTC
### Describe Your Problem

When I off the switchbot, it works fine. But the status changes to on after 10 seconds. It should be off until somebody changes to off.

### Relevant log output

```shell
[21/11/2021, 13:07:53] [SwitchBot] Bot: Bot 7E On: false
[21/11/2021, 13:08:03] [SwitchBot] [DEBUG] Bot: Bot 7E BLE parseStatus
[21/11/2021, 13:08:03] [SwitchBot] [DEBUG] Bot: Bot 7E On: true, BatteryLevel: 91
[21/11/2021, 13:08:27] [SwitchBot] [DEBUG] Bot: Bot 7E BLE refreshStatus
[21/11/2021, 13:08:37] [SwitchBot] [DEBUG] Bot: Bot 7E BLE parseStatus
[21/11/2021, 13:08:37] [SwitchBot] [DEBUG] Bot: Bot 7E On: true, BatteryLevel: 91
[21/11/2021, 13:10:27] [SwitchBot] [DEBUG] Bot: Bot 7E BLE refreshStatus
[21/11/2021, 13:10:37] [SwitchBot] [DEBUG] Bot: Bot 7E BLE parseStatus
[21/11/2021, 13:10:37] [SwitchBot] [DEBUG] Bot: Bot 7E On: true, BatteryLevel: 91
[21/11/2021, 13:12:27] [SwitchBot] [DEBUG] Bot: Bot 7E BLE refreshStatus
[21/11/2021, 13:12:37] [SwitchBot] [DEBUG] Bot: Bot 7E BLE parseStatus
[21/11/2021, 13:12:37] [SwitchBot] [DEBUG] Bot: Bot 7E On: true, BatteryLevel: 91
[21/11/2021, 13:13:57] [Homebridge UI] [@switchbot/homebridge-switchbot] Terminating child process...
[21/11/2021, 13:13:57] [Homebridge UI] [@switchbot/homebridge-switchbot] Child process ended
[21/11/2021, 13:14:27] [SwitchBot] [DEBUG] Bot: Bot 7E BLE refreshStatus
[21/11/2021, 13:14:37] [SwitchBot] [DEBUG] Bot: Bot 7E BLE parseStatus
[21/11/2021, 13:14:37] [SwitchBot] [DEBUG] Bot: Bot 7E On: true, BatteryLevel: 91
[21/11/2021, 13:16:27] [SwitchBot] [DEBUG] Bot: Bot 7E BLE refreshStatus
[21/11/2021, 13:16:37] [SwitchBot] [DEBUG] Bot: Bot 7E BLE parseStatus
[21/11/2021, 13:16:37] [SwitchBot] [DEBUG] Bot: Bot 7E On: true, BatteryLevel: 91
...
```

### Config for homebridge-switchbot

```shell
{
"name": "SwitchBot",
"credentials": {
"notice": "Keep your token a secret!"
},
"options": {
"devices": [
{
"deviceId": "XXXXXXXXXXXX",
"configDeviceName": "XXXX",
"configDeviceType": "Bot",
"ble": true,
"bot": {
"mode": "switch",
"deviceType": "switch"
}
}
],
"debug": "debug"
},
"_bridge": {
"username": "XX:XX:XX:XX:XX:XX",
"port": XXX
},
"platform": "SwitchBot"
}
```

### Screenshots
![スクリーンショット_2021-11-23_18_27_08](https://user-images.githubusercontent.com/7919609/142999864-44c47869-1e54-4cf1-93b9-d0a67f3425a1.png)
![スクリーンショット_2021-11-23_18_27_27](https://user-images.githubusercontent.com/7919609/142999880-d9d2e846-5f0b-4e90-a69e-3246ecdf68ef.png)

I used to use switchbot-ble plugin. It has been working without any problem.

I have updated the plugin to homebridge-switchbot. I disabled the switchbot-ble and configured the new plugin.
Now the new plugin (homebridge-switchbot v1.2.0) works. However, there is one issue.

The problem is the switchbot status as Homebridge changes to ON after 10 seconds automatically. Here is detail procedure:

1. I change the switchbot from ON to OFF by using either Homebridge Config UI or Apple Home app.
2. It works fine. The switchbot moves to OFF.
3. 10 seconds later, the switchbot status changes to ON automatically. Nobody changes the status. The switchbot doesn't move.

Please see the switchbot debug log. 1st line ([21/11/2021, 13:07:53]) means I change the switchbot status to OFF. Then 2nd and 3rd line ([21/11/2021, 13:08:03]) seems changing the switchbot status to ON. Then it repeats. I don't know why it happens.

### Device & Model

RaspberryPi 4B 4MB RAM

### Node.js Version

v16.13.0

### NPM Version

v8.1.0

### Homebridge Version

v1.3.8

### Homebridge SwitchBot Plugin Version

v1.2.0

### Operating System

Raspbian

**Comment by tzwada** [comment] 2021-11-22 05:25
My question will be:
- Are 2nd and 3rd line of plugin debug logs the reason why change the switchbot status from OFF to ON?
- If so, why does above action occur?

**Comment by donavanbecker** [comment] 2021-11-23 17:14
@tzwada, so you are using BLE only mode right? I was able to reproduce this so will have to see why this is occurring. do you have a hub? if so the OpenAPI connection is working, so I must have one little piece of code wrong.

**Comment by donavanbecker** [comment] 2021-11-23 20:04
@tzwada this is actually an issue with node-switchbot. What I am receiving back from the BLE API is a false which causes it to switch back to false after it goes through. 

The OpenAPI connection shows the state correctly, so if you are able to use the OpenAPI for now.

**Comment by nmcc1212** [comment] 2021-11-24 00:35
+1 am also having the same issue, although i didn't have this on the old plugin (just switched today)

**Comment by tzwada** [comment] 2021-11-24 10:13
@donavanbecker, thanks for reply. I use BLE only. I don't have a hub. I'd be happy to wait for fixing. If you need any additional information, please let me know.

**Comment by tzwada** [comment] 2021-12-10 06:31
@donavanbecker I switched back to switchbot-ble plugin to avoid this issue. It would be good if this issue will be fixed. Then I'd happy to back to use again.

**Comment by nmcc1212** [comment] 2021-12-10 10:03
i'm using this plugin to avoid this issue

https://github.com/ewebdev/homebridge-switchbot-ble

**Comment by raphaelmsr** [comment] 2021-12-19 12:09
So are we doomed into switching to homebridge-switchbot even if we only use BLE ?
My plugin keeps on asking the openToken but I don't need it ... Any ideas ?
How to reinstall homebridge-switchbot-ble?

**Comment by donavanbecker** [comment] 2021-12-19 12:15
> So are we doomed into switching to homebridge-switchbot even if we only use BLE ?
> 
> My plugin keeps on asking the openToken but I don't need it ... Any ideas ?
> 
> How to reinstall homebridge-switchbot-ble?

First, This plugin works in BLE only mode, I haven't had time to look at this issue yet, but hopefully will soon. Second, the plugin shouldn't be asking for the openToken on the latest version, because of the BLE only mode.

**Comment by raphaelmsr** [comment] 2021-12-19 12:20
> > So are we doomed into switching to homebridge-switchbot even if we only use BLE ?
> > My plugin keeps on asking the openToken but I don't need it ... Any ideas ?
> > How to reinstall homebridge-switchbot-ble?
> 
> First, This plugin works in BLE only mode, I haven't had time to look at this issue yet, but hopefully will soon. Second, the plugin shouldn't be asking for the openToken on the latest version, because of the BLE only mode.

The documentation is a bit opaque tbh; how do I activate the BLE only mode ?

**Comment by donavanbecker** [comment] 2021-12-19 12:33
Input deviceid and device name into SwitchBot device setting

**Comment by raphaelmsr** [comment] 2021-12-19 12:37
I am not using the Homebridge UI I have Hoobs installed
somehow the settings for the device does not recognise the "add devices" entry

I am setting up manually in the Advanced tab

this is how it looks right now 
`{
    "platform": "SwitchBot",
    "name": "SwitchBot",
    "credentials": {
        "notice": "Keep your token a secret!"
    },
    "options": {
        "devices": [
            {
                "deviceId": "XXXXXXXXX",
                "configDeviceName": "Hifi",
                "configDeviceType": "Bot",
                "ble": true,
            }
        ]
    },
    "devicediscovery": false
}`

Thanks for your answer!

**Comment by donavanbecker** [comment] 2021-12-19 15:45
@raphaelmsr That would be a HOOBs issue as I use Homebridge Plugin UI.

Either[ move to homebridge](https://github.com/homebridge/homebridge-raspbian-image/wiki/How-To-Migrate-From-HOOBS-To-Homebridge).

Or ask HOOBs to support the UI

**Comment by raphaelmsr** [comment] 2021-12-19 16:24
Cant you just tell me how to configure it JSON wise please? … there is very little documentation I am used to Homebridge UI, Hoobs, Homebridge without UI, theres always a way to configure it with the key value objects

>

**Comment by donavanbecker** [comment] 2021-12-19 16:41
@raphaelmsr, [Configuration Wiki](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Configuration)

**Comment by raphaelmsr** [comment] 2021-12-19 22:18
Thanks! Still no luck though, very weird

**Comment by donavanbecker** [comment] 2021-12-31 07:04
@tzwada and @raphaelmsr, can you try the latest beta: 

[![npm version](https://badgen.net/badge/homebridge-switchbot@beta/>=1.5.1-beta.5/orange)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

[Click here to find out how to install Beta](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Beta-Version)

**Comment by oleksiikutuzov** [comment] 2022-01-02 19:59
@donavanbecker seems to be fixed in v1.5.1-beta.5. Bot keeps its off state.

**Closed as completed** 2022-01-02 21:49 UTC
Labels: bug, pinned, BLE-API

**Comment by tzwada** [comment] 2022-01-08 00:11
@donavanbecker Sorry for late. I have updated the plugin to 1.7.0 (not 1.5.1-beta.5). But unsuccessful. When the plugin starts, it became generating an error as below:

[08/01/2022, 09:02:06] [SwitchBot] Total IR Devices Found: 0
[08/01/2022, 09:02:06] [SwitchBot] Bot: Bot 7E Using Bot Mode: switch
[08/01/2022, 09:02:06] [SwitchBot] Bot: Bot 7E Displaying as Switch
[08/01/2022, 09:02:07] [SwitchBot] Bot: Bot 7E wasn't able to establish BLE Connection
[08/01/2022, 09:02:07] [SwitchBot] Bot: Bot 7E Using OpenAPI Connection

As of above, now the plugin says it cannot establish BLE connection. Is this something I have to reconfigure? 
All settings are the same with my root article.

**Comment by tzwada** [comment] 2022-02-02 13:14
The problem was fixed. See https://github.com/OpenWonderLabs/homebridge-switchbot/issues/234#issuecomment-1027924156
