### ISSUE TITLE
Bug: min/max status not working 

### ISSUE THREAD

**Issue by yokouchi86** [OpenWonderLabs/homebridge-switchbot#170] opened 2021-12-28 16:04 UTC
### Describe The Bug

Min max has no effect to the open/close status

### To Reproduce

Set a min of 10% to indicate closing status and set less than 10% opening, it will continue showing opening in homekit

### Expected behavior

It should show close if it is less than 10% opening

### Relevant log output

```shell
N/a
```

### Config for homebridge-switchbot

```shell
N/a
```

### Screenshots

Not sure if my understanding is correct for this config, do let me know if I am wrong

### Device & Model

Switchbot curtain 

### Node.js Version

X

### NPM Version

X

### Homebridge Version

4.0.110

### Homebridge Switchbot Plugin Version

1.5

### Operating System

Hoobs

**Comment by donavanbecker** [comment] 2021-12-31 07:07
Duplicate of #123

**Closed as completed by donavanbecker** 2021-12-31 07:07 UTC
Labels: bug
