### ISSUE TITLE
Feature Request: Support for SwitchBot Blind Tilt

### ISSUE THREAD

**Issue by Gadgetfarmer** [OpenWonderLabs/homebridge-switchbot#654] opened 2023-01-18 00:04 UTC
### Problem

The current plugin don't have support for the SwitchBot Blind Tilt

### Solution

Support of the product

**Comment by donavanbecker** [comment] 2023-01-18 04:58
Duplicate of #649

**Closed as not planned by donavanbecker** 2023-01-18 04:59 UTC
Labels: enhancement
